
# メタ分析

-   理想的には、各研究に関連する先行研究の効果量をメタ分析によって統合し、得られた効果量分布に基づいて効果量の大きさを解釈するべきである。しかしながら、メタ分析においても様々な問題から、真の効果量分布を捉えられないことがある。

-   メタ分析は、先行研究から効果量を収集し、それらを評価した上で、特定のモデルによって統合するという手順で実施される。これらの過程において、どのような方法を採用するかに多くの研究者自由度がある。

-   効果量の収集段階では、どのような文献を対象にするかを研究者が決定する必要がある。査読付き論文の方が研究の質は高いかもしれないが、出版バイアスの影響で効果量分布を高く見積もる可能性がある。いわゆる灰色文献と呼ばれるような学位論文や紀要論文といった幅広い文献から効果量を収集した方が真の効果量分布に近づくかもしれない。また、英語で書かれた文献のみを収集すれば、効果量分布の一般化可能性を低下させるかもしれない。

-   効果量の質の評価の段階では、外れ値を評価して分析から除外する必要があるが、外れ値の検出方法にも様々な方法がある。例えば、外部標準化残差、クック距離、共分散比率、leave-one-out法、Graphic Display of Heterogeneity plotなど、様々な判断基準がある。また、出版バイアスの補正方法も、Egger検定、Petersの回帰検定、Trim & Fill法、PET-PEESE法、Pカーブ分析、など様々な方法があるが、どの方法を採用するかによって推定される効果量分布は変わってくる。

-   効果量を統合する際に使用するモデルにも、固定効果モデル、変量効果モデル、3-levelのマルチレベルモデルなど、様々な方法がある。推定法にも、DerSimonian-Laird、REML、Paule-Mandel、Empirical Bayes、Sidik-Jonkman、など様々な方法があり、効果量推定の不確実性にもどのような分布を適応させるかの選択肢がある（e.g., Knapp-Hartungの調整）。

-   このように、メタ分析を行う上では研究者が決定しなければいけない様々な分析の選択肢があり、選択によって推定される効果量の分布が変わってくる。また、そもそも出版バイアスがある場合、効果量の真の分布をとらえることは極めて困難である。

-   メタ分析の結果が真の効果量分布を捉えられていないならば、それを効果量の解釈の基準にすることには誤った解釈につながるというリスクが伴う。それでも、ベンチマークを機械的に当てはめることよりはましな推論ができるかもしれないが。
