% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  ja=standard, xelatex, base=12pt]{bxjsreport}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={効果量に関するまとめ},
  pdfauthor={Daiki Nakamura},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\usepackage{booktabs}
%\setjamonofont{SourceHanCodeJP-Light}
\setjamonofont{IPAexGothic}
\XeTeXgenerateactualtext=1
\usepackage{tikz}
\usepackage{makeidx}
\makeindex
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{効果量に関するまとめ}
\author{Daiki Nakamura}
\date{2022-07-06}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{ux30a4ux30f3ux30c8ux30edux30c0ux30afux30b7ux30e7ux30f3}{%
\chapter{イントロダクション}\label{ux30a4ux30f3ux30c8ux30edux30c0ux30afux30b7ux30e7ux30f3}}

\hypertarget{ux30c9ux30adux30e5ux30e1ux30f3ux30c8ux306eux6982ux8981}{%
\section{ドキュメントの概要}\label{ux30c9ux30adux30e5ux30e1ux30f3ux30c8ux306eux6982ux8981}}

本ドキュメントの目的は、効果量（effect size）の理論と計算法に関する基礎的な内容をまとめることにある。 具体的には、効果量の定義、種類、Rによる計算法、解釈、統合の方法などを扱う。

近年、多くの研究スタンダードが帰無仮説検定の結果としてp値だけでなく効果量とその信頼区間を報告することを求めている(e.g., \protect\hyperlink{ref-american2019publication}{APA, 2019, p. 89})。 しかしながら、効果量に関して網羅的にまとめられた日本語の無料ドキュメントが管見の限り無かったため、本ドキュメントの作成に至った。 著者は統計の専門家ではないため、読者自身で内容の正しさを確認しながら読み進めていただきたい。

\hypertarget{ux52b9ux679cux91cfux3068ux306fux4f55ux304b}{%
\section{効果量とは何か}\label{ux52b9ux679cux91cfux3068ux306fux4f55ux304b}}

効果量の記載を推奨する文献が多く存在する一方で、効果量の定義について述べた文献は驚くほど少ない(\protect\hyperlink{ref-dragicevic2020mean}{Dragicevic, 2020})。それでも数少ない例をあたれば、効果量に関する初期の定義は、効果量という言葉を広めた \href{https://en.wikipedia.org/wiki/Jacob_Cohen_(statistician)}{Jacob Cohen} の1977年の著作に見ることができる。

\begin{quote}
The ``effect size,'' that is, the degree to which the phenomenon exists. (\protect\hyperlink{ref-cohen1977statistical}{Cohen, 1977} , p.4)
\end{quote}

この記述から、Cohen自身は効果量を\textbf{ある現象が存在する程度を表す量}として捉えていたことが読み取れる。この表現の意味を正確に理解するためには、Neyman-Pearson流の統計的帰無仮説検定（ Null Hypothesis Significance Testing, NHST）の枠組みを考える必要がある。 NHSTの枠組みにおいて、帰無仮説はある現象が存在しない状態を表す仮説、対立仮説はある現象が存在する状態を表す仮説として設定されることが多い。 例えば、ある病気の発症率の性差を検討する場合、性別間で発症率に差がないという帰無仮説は、発症率の性差という現象が存在しないという状態を表現している。 他方で対立仮説は現象が存在する状態を表し、その強度が効果量として量的に表現されるのである。別の言い方をすれば、効果量は「帰無仮説が偽である程度」も意味する(\protect\hyperlink{ref-cohen1977statistical}{Cohen, 1977, pp. 9--10})。

効果量の定義に言及した最近の文献では、「効果量とは単に\textbf{研究者が関心を持つ事柄の大きさで}ある（原文：An effect size is simply the size of anything that may be of interest.）」とされている(\protect\hyperlink{ref-cumming2012understanding}{Cumming, 2012, p. 34})。Cohenの定義と異なり、現象の実在性を問題とせず研究者が関心を持つ対象の大きさとして扱っている点や、NHSTの枠組みに依存していない点が特徴的である。何を関心の対象とするかは研究者が自由に決めることができる。

これらの効果量の定義は広義の効果量と呼ばれ、狭義の効果量の定義とは区別されることがある。効果量には測定単位に依存しない形で表現される標準化効果量（e.g., Cohen's d）と、測定単位に依存する非標準化効果量（e.g., 平均値差）の2種類が存在する。広義の効果量の定義が両者を効果量に含めるのに対して、狭義の効果量の定義では標準化効果量のみを効果量として扱う。一部の文献では狭義の効果量の定義のみを効果量の定義として記載している(\protect\hyperlink{ref-everitt2010cambridge}{Everitt \& Skrondal, 2010}; \protect\hyperlink{ref-ialongo2016}{Ialongo, 2016})。この背景には、標準化効果量の方が研究間で比較しやすいという考えがあると推察される。Ives (\protect\hyperlink{ref-ives2003}{2003}) は理想的な効果量の特徴として、次の3点を挙げている。

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  結果の実質的な有意性を測るものである
\item
  標本サイズに依存しない
\item
  測定単位に依存しない
\end{enumerate}

このうち、3番目の特徴は標準化効果量のみが持つ性質だが、測定単位に依存しない（metric free）という性質は研究間に比較・統合の容易性や、検定力を分析する際の利便性などから重宝される。しかしながら、元の測定単位に意味のある状況では、標準化効果量より非標準化効果量の方が好まれることもある(\protect\hyperlink{ref-wilkinson1999}{Wilkinson, 1999, p. 599})。また、複数の標本統計量を用いて算出される標準化効果量は、単一の標本統計量を用いて算出される非標準化効果量と比べて不確実性が増加するという理由で使用に反対する意見も存在する(\protect\hyperlink{ref-cummings2011}{Cummings, 2011})。 よって、どちらか一方に限定せず、両方の種類を適宜使用することが望ましいと考えられる。

\href{https://en.wikipedia.org/wiki/Jacob_Cohen_(statistician)}{Jacob Cohen} 以降の効果量の定義についてレビューした Preacher and Kelley は、広義の定義が最も有用であると結論付けた上で、効果量を以下のように定義している。

\begin{quote}
We define effect size as any measure that reflects a quantity of interest, either in an absolute sense or as compared with some specified value. {[}\ldots{]} Although standardized effect sizes can be valuable, they are not always to be preferred over an effect size that is wedded to the original measurement scale, which may already be expressed in meaningful units that appropriately address the question of interest. (\protect\hyperlink{ref-preacher2011}{Preacher \& Kelley, 2011} , p.95)

（著者訳）効果量とは、絶対的な意味で、あるいはある特定の値と比較して、関心のある量を反映するあらゆる尺度であると定義する。（中略）標準化された効果量は有用であるが、非標準化効果量よりも常に優先されるとは限らず、興味のある問題に適切に対応する意味のある単位で既に表現されている場合もある。
\end{quote}

以上より、効果量の定義としては広義の定義を採用することが妥当だと考えられ、本ドキュメントも非標準化効果量と標準化効果量の両方を効果量として扱う。

なお、非標準化効果量という表現は標準化効果量の劣化版という誤った印象を与える可能性があることから、単純効果量（simple effect size）という表現を用いるべきだという主張も存在するが(e.g., \protect\hyperlink{ref-baguley2009}{Baguley, 2009, p. 239})、このような表現は少なくとも日本語圏ではあまり普及していないことから、本ドキュメントでは採用しない。

効果量の定義に関するその他の議論については、Dragicevic (\protect\hyperlink{ref-dragicevic2020mean}{2020}) や Kelley \& Preacher (\protect\hyperlink{ref-kelley2012}{2012}) などを参照されたい。

\hypertarget{ux52b9ux679cux91cfux3092ux5229ux7528ux3059ux308bux30e1ux30eaux30c3ux30c8}{%
\section{効果量を利用するメリット}\label{ux52b9ux679cux91cfux3092ux5229ux7528ux3059ux308bux30e1ux30eaux30c3ux30c8}}

効果量を利用することのメリットとして、Lakens (\protect\hyperlink{ref-lakens2013}{2013}) は次の3点を挙げている。

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  効果の大きさを示すことができる
\item
  研究間で効果の大きさを比較・統合することができる
\item
  過去の研究の効果量は、新しい研究を行う際の検定力分析に利用することができる
\end{enumerate}

Lakensはこれらのメリットを標準化効果量を前提として挙げているが、同様のメリットは非標準化効果量にも当てはまる。効果量を利用するメリットの1つは、従来のNHSTにおける帰無仮説が棄却できるかどうかの議論を超えて、どの程度の効果があるのかを定量的に示すことができる点にある。このような効果量は、同じ効果を表していて単位が共通であれば研究間で比較・統合することができる。例えば、今回得られた効果量が過去の研究と比べて大きいものなのかを比較することが考えられる。また、メタ分析のような効果量を量的統合方法は、母効果量や効果量の分布に関するより精度の高い推測を可能にする。このようにして蓄積された効果量の分布に関する情報は、新たな研究を行う際の検定力分析やサンプルサイズ設計に活用することができる。以上のように、研究において効果量を利用することには様々なメリットがある。

\hypertarget{ux52b9ux679cux91cfux306eux7a2eux985e}{%
\section{効果量の種類}\label{ux52b9ux679cux91cfux306eux7a2eux985e}}

効果量には様々な種類が提案されており、一説によればその数は40を超える(\protect\hyperlink{ref-kirk1996}{Kirk, 1996, pp. 748--749})。Hubertyは、効果量の種類と歴史的な登場時期を下図のように整理している(\protect\hyperlink{ref-huberty2002}{Huberty, 2002, fig. 1})。このように、効果量は長い時間をかけて様々な種類が提案されてきたものであって、一定の時期にまとめて提案されたものではない。最近でも新たな効果量は提案され続けている(e.g., robust effect size: \protect\hyperlink{ref-vandekar2020}{Vandekar et al., 2020})。

\begin{figure}
\centering
\includegraphics{images/paste-11880CB3.png}
\caption{効果量の歴史的展開. Figure from Huberty (\protect\hyperlink{ref-huberty2002}{2002})}
\end{figure}

効果量には様々な種類があるが、d族（d family）とr族（r family）に大別する分類がよく用いられる(\protect\hyperlink{ref-rosenthal1994}{Rosenthal, 1994, p. 234})。基本的に、d族の効果量は群間の平均値差に関する指標であり、r族の効果量はモデルで説明される分散の割合に関する指標である。このような分類は大まかな効果量の種類と共通した性質を整理する上では有用だが、これらの種類に当てはまらない効果量が存在することや、本ドキュメントの効果量の定義が非標準化効果量を含む広義の定義を採用していることを踏まえ、今回は採用しない。代わりに、より細かい効果量の分類に基づき、代表的な効果量の一部を以下の表のように整理した。表に示した効果量は、次章以降で具体的な計算法を紹介する。

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.1690}}
  >{\centering\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.1690}}
  >{\centering\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.6620}}@{}}
\caption{代表的な効果量（仮）}\tabularnewline
\toprule
\begin{minipage}[b]{\linewidth}\centering
種類
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
非標準化効果量
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
標準化効果量
\end{minipage} \\
\midrule
\endfirsthead
\toprule
\begin{minipage}[b]{\linewidth}\centering
種類
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
非標準化効果量
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
標準化効果量
\end{minipage} \\
\midrule
\endhead
平均値 & 平均値 & ー \\
平均値差 & 平均値差D & Cohen's \(d\), Hedges' \(g\), Glass's \(\Delta\) \\
相関 & 共分散COV & 積率相関 \(r\), 点双列相関 \(r_{pb}\) \\
分散比 & ー & \(\eta^2\) , \(\omega^2\) , \(\eta_{p}^2\) , \(\omega_p^2\) , \(\eta_{G}^2\) , \(\omega_{G}^2\) \\
比率 & ー & リスク比\(RR\) , オッズ比\(OR\) \\
\bottomrule
\end{longtable}

\hypertarget{ux7d71ux8a08ux30bdux30d5ux30c8ux30a6ux30a7ux30a2rux306eux6e96ux5099}{%
\section{統計ソフトウェアRの準備}\label{ux7d71ux8a08ux30bdux30d5ux30c8ux30a6ux30a7ux30a2rux306eux6e96ux5099}}

Rは無料の統計解析用ソフトウェアである。本ドキュメントでは、Rを用いて効果量に関する計算を実行する方法を示している。Rによる解析は効果量に関する理解を深める上で有用だと考えられるため、ぜひ実行しながら結果を確かめてほしい。Rの基本的な使い方に関しては無料の解説がWeb上に多く存在するため、そちらを参照されたい。

全ての分析はRだけでも実行可能だが、RStudioというソフトウェアからRを実行した方が利便性が高い。個人的には、\href{https://www.rstudio.com/products/rstudio/download/}{RStudioの無料版}を利用することをお勧めする。著者はWindows11 + R4.2.1 + RStudio2022.02.3 の環境で動作確認をしている。

また、本ドキュメントでは追加のパッケージとして、\texttt{easystats}を使用している。\texttt{easystats}は、様々な統計量を扱うパッケージ群を包括したものであり、効果量に関する分析を行う上では非常に便利である。

\begin{figure}
\centering
\includegraphics{images/logo_wall.png}
\caption{easystats パッケージ群}
\end{figure}

以下のコードで\texttt{easystats}に関連するパッケージ群をインストールできる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"easystats"}\NormalTok{, }\AttributeTok{repos =} \StringTok{"https://easystats.r{-}universe.dev"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux30ecux30f3ux30c0ux30eaux30f3ux30b0ux672cux306eux30d5ux30a1ux30a4ux30ebux4f5cux6210}{%
\subsubsection{レンダリング(本のファイル作成)}\label{ux30ecux30f3ux30c0ux30eaux30f3ux30b0ux672cux306eux30d5ux30a1ux30a4ux30ebux4f5cux6210}}

\begin{itemize}
\tightlist
\item
  gitbook形式: 以下のコードを実行
\end{itemize}

\begin{verbatim}
bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook")
\end{verbatim}

\begin{itemize}
\tightlist
\item
  epub形式: 以下のコードを実行
\end{itemize}

\begin{verbatim}
bookdown::render_book("index.Rmd", output_format = "bookdown::epub_book")
\end{verbatim}

\begin{itemize}
\tightlist
\item
  pdf形式: 以下のコードを実行
\end{itemize}

\begin{verbatim}
bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book")
\end{verbatim}

\hypertarget{ux5e73ux5747ux5024ux3068ux63a8ux6e2cux7d71ux8a08ux306eux57faux790e}{%
\chapter{平均値と推測統計の基礎}\label{ux5e73ux5747ux5024ux3068ux63a8ux6e2cux7d71ux8a08ux306eux57faux790e}}

本章では、多くの読者にとってなじみが深い指標であろう\textbf{平均値}（相加平均）が効果量として解釈可能であることを示した上で、正規母集団から得られた標本を用いて母平均\(\mu\) の点推定・区間推定を行うことを通して、推測統計の基礎を確認する。また、ベイズ統計に基づくアプローチについても紹介する。

\hypertarget{ux52b9ux679cux91cfux3068ux3057ux3066ux306eux5e73ux5747ux5024}{%
\section{効果量としての平均値}\label{ux52b9ux679cux91cfux3068ux3057ux3066ux306eux5e73ux5747ux5024}}

ある研究においてn個の観測値 \(x_1, x_2, ..., x_n\) が得られたとき、平均値は以下の式で計算できる。 \[
\bar{x}=\frac{1}{n}(x_1+x_2+...+x_n)=\frac{1}{n}\sum_{i=1}^{n}x_i
\] 平均は全観測値の重心を示すものであり、分布が左右対称の場合は全観測値の中心を示す。 研究間で同一の測定が実現しているとき、各研究から得られた平均値を比較可能である。 特に、元の測定単位における比較に関心がある場合、平均値を比較することは有用かもしれない。

\hypertarget{ux6bcdux5e73ux5747ux306eux63a8ux5b9a}{%
\section{母平均の推定}\label{ux6bcdux5e73ux5747ux306eux63a8ux5b9a}}

母集団における平均（母平均\(\mu\)）を知りたい場合、理想的には全数調査を行い平均値を計算すればよいが、このような調査はコストがかかるため多くの場合、現実的ではない。そこで、母集団からの抽出された標本を用いて母平均\(\mu\)を推定することを考える。

標本調査によって、平均\(\mu=5\)、分散\(\sigma^2=1\)の正規分布に独立に従う100個の標本が得られたとする。\[
x_1, x_2, ..., x_{100} \sim \mathcal{N}(5, 1)
\] 実際には、得られた標本がどのような母数の分布に従うかは多くの場合、未知である。 得られた標本から母平均を推定することを考えてみよう。

\hypertarget{ux70b9ux63a8ux5b9a}{%
\subsection{点推定}\label{ux70b9ux63a8ux5b9a}}

標本から母平均 \(\mu\) を点推定する場合、推定量には標本平均 \(\bar{x}\) を用いる。 これは、大数の法則より、標本平均 \(\bar{x}\) はサンプルサイズ \(n\) が大きくなると母平均 \(\mu\) に近づくという\textbf{一致性}を持つからである（\(\bar{x}\stackrel{p}{\longrightarrow}\mu\)）。 また、標本平均 \(\bar{x}\) の期待値 \(E[\bar{x}]=\mu\) となることから、サンプルサイズ \(n\) に関係なく標本平均 \(\bar{x}\) の期待値は母平均に一致するという\textbf{不偏性}を持つ。 よって、標本平均 \(\bar{x}\) は母平均 \(\mu\) の一致推定量かつ不偏推定量である。

このことを確かめるために、Rを使用して以下のようなシミュレーションを行ってみよう。ここでは毎回同じ結果が再現されるよう乱数の種を固定したうえで、平均 \(\mu=5\)、分散 \(\sigma^2=1\) の正規分布に独立に従う \(n\)個の乱数を発生させ、それらの標本平均を求めるシミュレーションを \(k\)回繰り返している。例えば、サンプルサイズ \(n=100\) の標本平均を算出することを1000回繰り返すと、その平均は5.000977になることが分かる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \ConstantTok{NULL} \CommentTok{\# 結果の格納用}
\NormalTok{n }\OtherTok{=} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\NormalTok{k }\OtherTok{=} \DecValTok{1000}  \CommentTok{\# シミュレーション回数}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{) }\CommentTok{\# 乱数の種の固定}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{k)\{}
\NormalTok{  dat }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{5}\NormalTok{, }\DecValTok{1}\NormalTok{) }\CommentTok{\# 正規分布N(5,1)からn個の乱数を発生}
\NormalTok{  m[i] }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(dat)     }\CommentTok{\# 標本平均の格納}
\NormalTok{\}}
\FunctionTok{mean}\NormalTok{(m)   }\CommentTok{\# k個の標本平均の平均}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.000977
\end{verbatim}

\(n\) や \(k\) の値を変えながら様々な条件で標本平均の計算を繰り返すと以下のような結果が得られる。

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1039}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1299}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1169}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1299}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1299}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1299}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1299}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1299}}@{}}
\caption{標本平均のシミュレーション}\tabularnewline
\toprule
\begin{minipage}[b]{\linewidth}\raggedright
k \textbackslash{} n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
1
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
5
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
10
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
20
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
100
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
1000
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
10000
\end{minipage} \\
\midrule
\endfirsthead
\toprule
\begin{minipage}[b]{\linewidth}\raggedright
k \textbackslash{} n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
1
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
5
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
10
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
20
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
100
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
1000
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
10000
\end{minipage} \\
\midrule
\endhead
1 & 4.439524 & 5.19357 & 5.074626 & 5.141624 & 5.090406 & 5.016128 & 4.997628 \\
100 & 5.090406 & 5.03459 & 5.016128 & 5.029297 & 4.997628 & 5.000977 & 4.999479 \\
1000 & 5.016128 & 4.99943 & 4.997628 & 4.994261 & 5.000977 & 4.999479 & 5.000115 \\
10000 & 4.997628 & 4.99826 & 5.000977 & 5.003096 & 4.999479 & 5.000115 & 5.000157 \\
100000 & 5.000977 & 5.00006 & 4.999479 & 4.998962 & 5.000115 & 5.000157 & 5.000010 \\
\bottomrule
\end{longtable}

表より、シミュレーション回数 \(k=1\) の行を横に見ると、サンプルサイズ \(n\) が増加するにつれて、標本平均 \(\bar{x}\) が母平均 \(\mu=5\) に近づく一致性が確認できる。また、シミュレーション回数 \(k=100000\) の行を横に見ると、サンプルサイズ \(n\) に関係なく標本平均 \(\bar{x}\) の期待値が \(\bar{x}\) が母平均 \(\mu=5\) に一致する不偏性が確認できる。

\hypertarget{ux533aux9593ux63a8ux5b9a}{%
\subsection{区間推定}\label{ux533aux9593ux63a8ux5b9a}}

点推定が母数を標本から得られる1つの値で推定したのに対して、区間推定では標本から得られる2つの値で母数が含まれる区間を推定する。

点推定の場合と同様、平均\(\mu=5\)、分散\(\sigma^2=1\)の正規分布に独立に従う100個の標本が得られているとする。ここで標本平均の標本分布が\(\mathcal{N}(\mu, \sigma^2/n)\) に従うことを利用すれば、任意の確率で母平均を含む信頼区間（Confidence Interval）を構成することができる。

\hypertarget{ux6bcdux5206ux6563ux65e2ux77e5ux306eux5834ux5408}{%
\subsubsection{母分散既知の場合}\label{ux6bcdux5206ux6563ux65e2ux77e5ux306eux5834ux5408}}

母分散が既知の場合、95\%信頼区間は、以下の式で求められる。 \[
\bar{x}-1.96\frac{\sigma}{\sqrt{n}}\leq\mu\leq\bar{x}+1.96\frac{\sigma}{\sqrt{n}}
\] 上式は母数を含んでいるため、標本から直接計算することはできない。 すでに先行研究などから母分散が分かっている場合、その値を代入して計算すればよい。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{100} \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{) }\CommentTok{\# 乱数の種の固定}
\NormalTok{x }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{5}\NormalTok{, }\DecValTok{1}\NormalTok{) }\CommentTok{\# 正規分布N(5,1)から100個の乱数を発生}
\NormalTok{m }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(x) }\CommentTok{\# 標本平均}
\NormalTok{m }\SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\DecValTok{1}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n) }\CommentTok{\# 95\%信頼区間の下限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.894406
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\DecValTok{1}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n) }\CommentTok{\# 95\%信頼区間の上限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.286406
\end{verbatim}

\hypertarget{ux6bcdux5206ux6563ux672aux77e5ux306eux5834ux5408}{%
\subsubsection{母分散未知の場合}\label{ux6bcdux5206ux6563ux672aux77e5ux306eux5834ux5408}}

母分散が未知でもnが十分に大きい場合は、標本の標準偏差を\(\sigma\)に代入して計算してもよい（一致性があるため）。 母分散が未知でnが小さい場合、\(\frac{\bar{x}-\mu}{\sigma/\sqrt{n}}\) が自由度 \(n-1\) のｔ分布に従うことを利用して、95\%信頼区間は以下の式で求められる。 ここで、\(\hat{\sigma}\) は母標準偏差の推定値であり、標本の標準偏差を代入して計算する。\[
\bar{x}-t_{0.025}(n-1)\frac{\hat{\sigma}}{\sqrt{n}}\leq\mu\leq\bar{x}+t_{0.975}(n-1)\frac{\hat{\sigma}}{\sqrt{n}}
\] Rでは、\texttt{qt()}を用いてｔ分布の任意の確率点を算出することができる。サンプルサイズを \(n=20\) に変更して、95\%信頼区間を求めてみよう。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{20}             \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)       }\CommentTok{\# 乱数の種の固定}
\NormalTok{x }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{5}\NormalTok{, }\DecValTok{1}\NormalTok{) }\CommentTok{\# 正規分布N(5,1)からn個の乱数を発生}
\NormalTok{m }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(x)        }\CommentTok{\# 標本平均}
\NormalTok{s }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(x)          }\CommentTok{\# 標準偏差}
\NormalTok{m }\SpecialCharTok{{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.025}\NormalTok{, n}\DecValTok{{-}1}\NormalTok{, }\AttributeTok{lower.tail =}\NormalTok{ F)}\SpecialCharTok{*}\NormalTok{s}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n) }\CommentTok{\# 95\%信頼区間の下限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.686402
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\SpecialCharTok{+} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\NormalTok{s}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)                }\CommentTok{\# 95\%信頼区間の上限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.596845
\end{verbatim}

既存の関数を利用して95\%信頼区間を求めても結果は一致する。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(x)}\SpecialCharTok{$}\NormalTok{conf.int     }\CommentTok{\# 既存の関数を利用した場合}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.686402 5.596845
## attr(,"conf.level")
## [1] 0.95
\end{verbatim}

95\%信頼区間の意味するところは、標本調査を何回も繰り返してその度に95\%信頼区間を構成した場合、95\%の確率でそれらの区間内に母数が含まれている区間であるということである。 個々の信頼区間が母数を含むかどうかはTrue/Falseの2択であり、確率的な表現ができているわけではない。 実験を何回も繰り返すことのできる研究分野や様々な研究者によって類似の研究が繰り返される分野では、信頼区間の概念が想像しやすいだろう。 他方で、実験を繰り返すことが困難な分野では、1回の調査で得られたデータから任意の確率で母数を含む区間を構成したいと考えるかもしれない。 そこで、次の節ではベイズ統計の考え方を紹介し、ベイズ信用区間（Credible Interval）を構成する。

\hypertarget{ux30d9ux30a4ux30baux7d71ux8a08ux306bux57faux3065ux304fux30a2ux30d7ux30edux30fcux30c1}{%
\section{ベイズ統計に基づくアプローチ}\label{ux30d9ux30a4ux30baux7d71ux8a08ux306bux57faux3065ux304fux30a2ux30d7ux30edux30fcux30c1}}

いま、正規母集団 \(\mathcal{N}(\mu, \sigma^2)\) から大きさｎのデータを得たとする。この標本から母平均 \(\mu\) を区間推定することを考える。ベイズ統計では、母数に関する事前の信念を確率モデルを用いて表現する（事前分布）。そして、ベイズの定理を用いて、事前分布と尤度から、データを得た後の事後分布を求める。

ここでは、母分散が既知であるのに対して、母平均 \(\mu\) に関して少ない情報しか持っておらず、 \(\mu\) の事前分布を一様分布と設定したとしよう。観測されたデータを用いて事前分布を更新すれば、事後分布は \(\mathcal{N}(\bar{x}, \sigma/\sqrt{n})\) になる。この事後分布を利用して95\%の確率で母平均 \(\mu\) を含む区間を構成すれば、95\%信用区間は以下の通りになる。

\[
\bar{x}-1.96\frac{\sigma}{\sqrt{n}}\leq\mu\leq\bar{x}+1.96\frac{\sigma}{\sqrt{n}}
\]

こうして構成した信用区間は、信頼区間とまったく異なる概念であることに注意が必要である。95\%信用区間は、その区間内に95\%の確率で母数が存在すると信用できる区間である。繰り返しの調査を前提とする必要はない。

\hypertarget{ux7d50ux679cux306eux5831ux544a}{%
\section{結果の報告}\label{ux7d50ux679cux306eux5831ux544a}}

非標準化効果量として平均値を報告する際には、以下の3点を報告すればよい。

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  母平均の推定値（標本平均）
\item
  推定値の不確かさ（95\%信頼区間など）
\item
  推定値の単位
\end{enumerate}

例）今回得られた標本における長さの平均は5.14cm, 95\% CI {[}4.69, 5.60{]} であった。

\hypertarget{ux5e73ux5747ux5024ux5deeux306eux52b9ux679cux91cf}{%
\chapter{平均値差の効果量}\label{ux5e73ux5747ux5024ux5deeux306eux52b9ux679cux91cf}}

本章では、２群間の平均値差に関する効果量とその信頼区間の計算方法を紹介する。平均値差に関する標準化効果量には複数の種類が存在するが、研究によってそれらの呼び方や使用する記号が異なることがあるので注意が必要である。

\hypertarget{ux72ecux7acbux3057ux305f2ux7fa4ux306eux5e73ux5747ux5024ux5dee}{%
\section{独立した2群の平均値差}\label{ux72ecux7acbux3057ux305f2ux7fa4ux306eux5e73ux5747ux5024ux5dee}}

2つの独立した母集団A, Bから抽出した2標本の平均値差について検討する。いま、2つの正規母集団 \(\mathcal{N_A}(60, 100), \mathcal{N_B}(50, 100)\) から無作為抽出によって100個ずつ（\(m=100, n=100\)）の独立な標本を得たとする。\[
A_1, A_2, ..., A_{m} \sim \mathcal{N}(60, 100),\\
B_1, B_2, ..., B_{n} \sim \mathcal{N}(50, 100)
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(50,100)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\end{Highlighting}
\end{Shaded}

\includegraphics{book_filename_files/figure-latex/unnamed-chunk-5-1.pdf}

独立した2群の平均値差を示す効果量には、非標準化平均値差と標準化平均値差の2種類がある。また、後者については、等分散が仮定できる場合とできない場合に分けて考えることができる。以下で順に紹介していく。

\hypertarget{ux975eux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee}{%
\subsection{非標準化平均値差}\label{ux975eux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee}}

2群の平均値差Dは、以下の式で求められる。これは、平均値と同様に非標準化効果量の一種であり、元の測定単位における比較に関心がある場合などに有用である。

\[
平均値差D=\bar{A}-\bar{B}
\] 平均値差Dは、母平均値差 \(\mu_A-\mu_B\) の一致推定量かつ不偏推定量であり、平均\(\mu_A-\mu_B\)、分散 \(\sigma_A^2/m+\sigma_B^2/n\) の正規分布に従う。母分散が既知の場合は、以下のように95\%信頼区間を構成すればよい。

\[
D-1.96\sqrt{\frac{\sigma_A^2}{m}+\frac{\sigma_B^2}{n}}\leq\mu_A-\mu_B\leq D+1.96\sqrt{\frac{\sigma_A^2}{m}+\frac{\sigma_B^2}{n}}
\] Rを利用すれば、以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{D }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(A) }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(B)     }\CommentTok{\# 非標準化平均値差}
\NormalTok{D }\SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{100}\SpecialCharTok{/}\NormalTok{m}\SpecialCharTok{+}\DecValTok{100}\SpecialCharTok{/}\NormalTok{n) }\CommentTok{\# 95\%信頼区間の下限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.207668
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{D }\SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{100}\SpecialCharTok{/}\NormalTok{m}\SpecialCharTok{+}\DecValTok{100}\SpecialCharTok{/}\NormalTok{n) }\CommentTok{\# 95\%信頼区間の上限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 14.75139
\end{verbatim}

母分散が未知であるが集団間で等しいことが分かっている場合、2群に共通した分散を以下の通り求めて、母分散の推定値として利用する。ここで、\(\hat\sigma_A^2\) は群Aの不偏分散、\(\hat\sigma_B^2\) は群Bの不偏分差を指す。 \[
\hat\sigma^2=\frac{(m-1)\hat\sigma_A^2+(n-1)\hat\sigma_B^2}{m+n-2} 
\] 平均値差の標本分布として、正規分布ではなく自由度 \(m+n-2\) のｔ分布を利用して、以下の通り95\%信頼区間を求める。 \[
D-t_{0.025}(m+n-2)\sqrt{\frac{\hat\sigma^2}{m}+\frac{\hat\sigma^2}{n}}\leq\mu_A-\mu_B\leq D+t_{0.975}(m+n-2)\sqrt{\frac{\hat\sigma^2}{m}+\frac{\hat\sigma^2}{n}}
\] Rを利用すれば、以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pooled\_var }\OtherTok{\textless{}{-}}\NormalTok{ ((m}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{var}\NormalTok{(A)}\SpecialCharTok{+}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{var}\NormalTok{(B))}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{+}\NormalTok{n}\DecValTok{{-}2}\NormalTok{)  }\CommentTok{\# 2群に共通した分散の推定値}
\NormalTok{D }\SpecialCharTok{{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.025}\NormalTok{, m}\SpecialCharTok{+}\NormalTok{n}\DecValTok{{-}2}\NormalTok{, }\AttributeTok{lower.tail =}\NormalTok{ F)}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(pooled\_var}\SpecialCharTok{/}\NormalTok{m }\SpecialCharTok{+}\NormalTok{ pooled\_var}\SpecialCharTok{/}\NormalTok{n)  }\CommentTok{\# 95\%信頼区間の下限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.357192
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{D }\SpecialCharTok{+} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, m}\SpecialCharTok{+}\NormalTok{n}\DecValTok{{-}2}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(pooled\_var}\SpecialCharTok{/}\NormalTok{m }\SpecialCharTok{+}\NormalTok{ pooled\_var}\SpecialCharTok{/}\NormalTok{n)                  }\CommentTok{\# 95\%信頼区間の上限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 14.60186
\end{verbatim}

既存の関数を利用して95\%信頼区間を求めても結果は一致する。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(A, B, }\AttributeTok{var.equal =}\NormalTok{ T)}\SpecialCharTok{$}\NormalTok{conf.int}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  9.357192 14.601862
## attr(,"conf.level")
## [1] 0.95
\end{verbatim}

\hypertarget{ux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee}{%
\subsection{標準化平均値差}\label{ux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee}}

2群の標準化平均値差に関する母効果量\(\delta\)は以下の式で定義される。 \[
\delta=\frac{μ_A-μ_B}{σ}
\]ここで\(μ_A\)，\(μ_B\)はそれぞれ群A, 群Bの母平均、\(σ\)は2群に共通な母標準偏差である。

得られた標本から母効果量\(\delta\)を推定する場合、その推定量を標本効果量と呼ぶ。 標準化平均値差の標本効果量にはいくつかの種類が提案されている。等分散を仮定する場合と等分散を仮定しない場合に分けて順に紹介する。

使用するデータは前節と同様である。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(50,100)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\end{Highlighting}
\end{Shaded}

なお、統計的帰無仮説検定によって2群の平均値差を検討する方法としてはｔ検定が知られており、検定統計量ｔがｔ分布に従うことを利用して、群間で平均値に差が無いという帰無仮説を棄却できるかどうかを判断する。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(A, B, }\AttributeTok{var.equal =}\NormalTok{ T) }\CommentTok{\# 等分散を仮定する場合（Student\textquotesingle{}s t{-}test）}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Two Sample t-test
## 
## data:  A and B
## t = 9.0087, df = 198, p-value < 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   9.357192 14.601862
## sample estimates:
## mean of x mean of y 
##  60.90406  48.92453
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(A, B, }\AttributeTok{var.equal =}\NormalTok{ F) }\CommentTok{\# 等分散を仮定しない場合（Welch\textquotesingle{}s t{-}test）}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  A and B
## t = 9.0087, df = 197.35, p-value < 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   9.357138 14.601916
## sample estimates:
## mean of x mean of y 
##  60.90406  48.92453
\end{verbatim}

\hypertarget{ux7b49ux5206ux6563ux3092ux4eeeux5b9aux3059ux308bux5834ux5408}{%
\subsection{等分散を仮定する場合}\label{ux7b49ux5206ux6563ux3092ux4eeeux5b9aux3059ux308bux5834ux5408}}

等分散を仮定する場合の標本効果量は主に2種類ある。 これは、2つの集団の分散をどのような計算式で統合（pool）するかの違いである。分散を統合する計算式には、標本分散を用いるものと不偏分散を用いるものがある。

標本分散を用いて統合する場合、以下の式になる。ここで、\(s_A^2\) は群Aの標本分散、\(s_B^2\) は群Bの標本分差を指す。

\[
s_A^2=\frac{1}{m}\sum_{i=1}^{m}(A_i-\bar{A}), s_B^2=\frac{1}{n}\sum_{i=1}^{n}(B_i-\bar{B}), \\
s_{pooled}=\sqrt\frac{ms_A^2+ns_B^2}{m+n}
\] Rを利用すれば、以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Va }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(A)}\SpecialCharTok{*}\NormalTok{(m}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{/}\NormalTok{m  }\CommentTok{\# Aの標本分散}
\NormalTok{Vb }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(B)}\SpecialCharTok{*}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{/}\NormalTok{n  }\CommentTok{\# Bの標本分散}
\NormalTok{s\_pooled }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{((m}\SpecialCharTok{*}\NormalTok{Va}\SpecialCharTok{+}\NormalTok{n}\SpecialCharTok{*}\NormalTok{Vb)}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{+}\NormalTok{n))}
\end{Highlighting}
\end{Shaded}

不偏分散を用いて統合する場合、以下の式になる。ここで、\(\hat\sigma_A^2\) は群Aの不偏分散、\(\hat\sigma_B^2\) は群Bの不偏分差を指す。

\[
\hat\sigma_A^2=\frac{1}{m-1}\sum_{i=1}^{m}(A_i-\bar{A}), \hat\sigma_B^2=\frac{1}{n-1}\sum_{i=1}^{n}(B_i-\bar{B}) \\
\hat\sigma=\sqrt\frac{(m-1)\hat\sigma_A^2+(n-1)\hat\sigma_B^2}{m+n-2}
\] Rを利用すれば、以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sigma }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(((m}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{var}\NormalTok{(A)}\SpecialCharTok{+}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{var}\NormalTok{(B))}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{+}\NormalTok{n}\DecValTok{{-}2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

2種類の推定量の間には、以下のような関係がある。 \[
\hat\sigma=s_{pooled}\sqrt{\frac{m+n}{m+n-2}}
\]

2種類の推定量を用いることでそれぞれ、Hedges \& Olkin の \(d\) とCohenの \(d_s\) という効果量が計算できる。順に紹介していく。

\hypertarget{hedges-olkins-d}{%
\subsubsection{\texorpdfstring{Hedges \& Olkin's \(d\)}{Hedges \& Olkin's d}}\label{hedges-olkins-d}}

1つ目は、Hedges \& Olkin の \(d\)であり、平均値差を2群に共通した標準偏差（\(s_{pooled}\)）で割ることで得られる。これは、母効果量\(\delta\)の最尤推定量である(\protect\hyperlink{ref-hedges1985}{Hedges \& Olkin, 1985})。この式で計算したものを Cohen's \(d\) と表現している文献もあるので、注意が必要である。

\[
d =\frac{\bar{A}-\bar{B}}{s_{pooled}} 
\]

誤差分散は以下の式で求められる。誤差分散の平方根を求めれば標準誤差になる。

\[
V_d=\frac{m+n}{mn}+\frac{d^2}{2(m+n-2)}
\] Rを利用すれば、Hedges \& Olkin の \(d\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\FunctionTok{mean}\NormalTok{(A)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(B))}\SpecialCharTok{/}\NormalTok{s\_pooled  }\CommentTok{\# Hedges \& Olkin\textquotesingle{}s d}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.280441
\end{verbatim}

\hypertarget{cohens-d_s}{%
\subsubsection{\texorpdfstring{Cohen's \(d_s\)}{Cohen's d\_s}}\label{cohens-d_s}}

2つ目は、Cohenの \(d_s\) であり、平均値差を2群に共通した標準偏差（\(\hat\sigma\)）で割ることで得られる(\protect\hyperlink{ref-cohen1988}{Cohen, 1988})。この式で計算したものを Cohen's \(d\) や Hedges' \(g\) と表現している文献もあるので、注意が必要である。名称の混乱問題については本章の最後で解説する。

\[
Cohen's~d_s =\frac{\bar{A}-\bar{B}}{\hat\sigma} 
\] 誤差分散は以下の式で求められる。誤差分散の平方根を求めれば標準誤差になる。 \[
V_{d_s}=\frac{m+n}{mn}+\frac {d_s^2}{2(m+n)} 
\] Rを利用すれば、Cohenの \(d_s\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\FunctionTok{mean}\NormalTok{(A)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(B))}\SpecialCharTok{/}\NormalTok{sigma  }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.274023
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{cohens\_d}\NormalTok{(A, B)  }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 1.27      | [0.97, 1.58]
## 
## - Estimated using pooled SD.
\end{verbatim}

\hypertarget{ux7b49ux5206ux6563ux3092ux4eeeux5b9aux3057ux306aux3044ux5834ux5408}{%
\subsection{等分散を仮定しない場合}\label{ux7b49ux5206ux6563ux3092ux4eeeux5b9aux3057ux306aux3044ux5834ux5408}}

\hypertarget{glasss-delta}{%
\subsubsection{\texorpdfstring{Glass's \(\Delta\)}{Glass's \textbackslash Delta}}\label{glasss-delta}}

等分散を仮定しない場合の標本効果量としては、Glassの \(\Delta\) がある。 これは、実験デザインに由来して群間で分散が異なることが想定される場合に有用である。 例えば、実験群にのみ介入を行い、その介入が分散を拡大させると考えられる場合、介入を行っていない統制群の分散の推定値を効果量の計算に用いる方が適切だと考えられる(\protect\hyperlink{ref-grissom2001}{Grissom \& Kim, 2001})。Glassの \(\Delta\) はこのような考え方に基づき、2群のうち片方の群の分散（標準偏差）のみを用いて効果量を計算する。

なお、使用するデータは、分散を変更している。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{12}\NormalTok{) }\CommentTok{\# 正規分布N(50,144)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\end{Highlighting}
\end{Shaded}

Glassの \(\Delta\) は以下の計算式の通り、平均値差を片方の群（統制群）の標準偏差で割ることで得られる(\protect\hyperlink{ref-glass1981}{Glass et al., 1981})。ここで、\(\hat\sigma_B^2\) は群Bの不偏分差を指す。ここでは、群Bが統制群であることを想定している。

\[
Glass's~\Delta =\frac{\bar{A}-\bar{B}}{\hat\sigma_B} 
\]

誤差分散は以下の式で求められる(\protect\hyperlink{ref-kline2004}{Kline, 2004, p. 108})。\[
V_{\Delta}=\frac{m+n}{mn}+\frac {\Delta^2}{2(n-1)} 
\] Rを利用すれば、Glassの \(\Delta\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\FunctionTok{mean}\NormalTok{(A)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(B))}\SpecialCharTok{/}\FunctionTok{sd}\NormalTok{(B)  }\CommentTok{\# Glass\textquotesingle{}s delta}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.25755
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{glass\_delta}\NormalTok{(A, B)  }\CommentTok{\# Glass\textquotesingle{}s delta}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Glass' delta |       95% CI
## ---------------------------
## 1.26         | [0.91, 1.60]
\end{verbatim}

\hypertarget{cohens-d_s-1}{%
\subsubsection{\texorpdfstring{Cohen's \(d_s\)}{Cohen's d\_s}}\label{cohens-d_s-1}}

なお、等分散が仮定できるが、分散の推定値に群間で差があった場合は、両群の情報を活用できる \(d\) や \(d_s\) を使用した方がいいだろう(\protect\hyperlink{ref-grissom2001}{Grissom \& Kim, 2001})。例えば、分散の推定値に群間で差があった場合のCohenの \(d_s\) は以下の通り計算することが推奨されている(\protect\hyperlink{ref-delacre2021}{Delacre et al., 2021})。ここで、\(\hat\sigma_A^2\) は群Aの不偏分散、\(\hat\sigma_B^2\) は群Bの不偏分差を指す。

\[
Cohen's~d_s=\frac{\bar{A}-\bar{B}}{\sqrt{(\hat\sigma_A^2+\hat\sigma_B^2)/2}}
\]

Rを利用すれば、分散が異なる場合のCohenの \(d_s\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\FunctionTok{mean}\NormalTok{(A)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(B))}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{((}\FunctionTok{var}\NormalTok{(A)}\SpecialCharTok{+}\FunctionTok{var}\NormalTok{(B))}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.176983
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{cohens\_d}\NormalTok{(A, B, }\AttributeTok{pooled\_sd =}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 1.18      | [0.87, 1.48]
## 
## - Estimated using un-pooled SD.
\end{verbatim}

\hypertarget{ux4fe1ux983cux533aux9593}{%
\subsection{信頼区間}\label{ux4fe1ux983cux533aux9593}}

標準化平均値差の効果量の信頼区間を算出する方法には、1．標準誤差を用いる方法、2．非心ｔ分布に基づく方法、3．ブートストラップ法の3種類がある(\protect\hyperlink{ref-inoue2008}{井上俊哉, 2008})。以下で順に紹介する。なお、使用するデータは以下の通りである。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(50,100)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux6a19ux6e96ux8aa4ux5deeux3092ux7528ux3044ux308bux65b9ux6cd5}{%
\subsubsection{標準誤差を用いる方法}\label{ux6a19ux6e96ux8aa4ux5deeux3092ux7528ux3044ux308bux65b9ux6cd5}}

1つ目は、標準誤差 \(se\)（誤差分散\(V_{\hat\delta}\)の平方根）を用いる簡易的な方法である。効果量の標本分布を正規分布で近似することで、95％信頼区間は以下のように計算できる(\protect\hyperlink{ref-nakagawa2007}{Nakagawa \& Cuthill, 2007})。ここで、\(\hat\delta\) は、母効果量 \(\delta\) の推定値である標本効果量（\(d, d_S, \Delta\)）を指す。

\[
\hat{\delta}-1.96*se\leq\delta\leq\hat{\delta}+1.96*se
\]

例えば、Cohen's \(d_s\) の95\%信頼区間は以下のように求められる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{ds }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)  }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\NormalTok{se\_ds }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{((m}\SpecialCharTok{+}\NormalTok{n)}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{*}\NormalTok{n)}\SpecialCharTok{+}\NormalTok{(ds}\SpecialCharTok{$}\NormalTok{Cohens\_d}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{(m}\SpecialCharTok{+}\NormalTok{n))))}
\NormalTok{ds}\SpecialCharTok{$}\NormalTok{Cohens\_d }\SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\NormalTok{se\_ds  }\CommentTok{\# 95\%信頼区間の下限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9700153
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ds}\SpecialCharTok{$}\NormalTok{Cohens\_d }\SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\NormalTok{se\_ds  }\CommentTok{\# 95\%信頼区間の上限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.57803
\end{verbatim}

しかし、これは簡易的な方法であって、正確ではない。より正確な方法としては次の2種類がある。

\hypertarget{ux975eux5fc3uxff54ux5206ux5e03ux306bux57faux3065ux304fux65b9ux6cd5}{%
\subsubsection{非心ｔ分布に基づく方法}\label{ux975eux5fc3uxff54ux5206ux5e03ux306bux57faux3065ux304fux65b9ux6cd5}}

2つ目は、非心ｔ分布を用いる方法である。これは、以下の式で計算される検定統計量\(t\)が帰無仮説が偽のときに、非心度\(λ\)、自由度\(df\)の非心ｔ分布に従うことを利用する方法である。

\[
t=d_s*\sqrt{\frac{mn}{m+n}},\\
\lambda=\delta*\sqrt{\frac{mn}{m+n}},\\
df=m+n-2
\]

今回の例の場合、自由度\(df=198\)の非心ｔ分布を非心度\(λ\)を変えながら描いていったとき、検定統計量\(t\)の実現値\(t=9.008702\)が上側確率0.975に一致する非心度\(λ_L\)を求める。そして、それに\(\sqrt{\frac{mn}{m+n}}\) をかけることで効果量\(\delta\)に変換したものが効果量\(d_s\)の信頼区間の上限値になる。同様に、検定統計量\(t\)の実現値が非心ｔ分布の下側確率0.025に一致する非心度\(λ_H\)を求めて変換すれば効果量\(d_s\)の信頼区間の下限値になる。非心ｔ分布の詳細については、(\protect\hyperlink{ref-haebara2014}{南風原朝和, 2014})などを参照されたい。※Glass's \(\Delta\) の場合は、自由度\(df\)を\(n-1\)とする。

Rを利用すれば、Cohen's \(d_s\) の95\%信頼区間は以下のように求められる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{ds }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)  }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\NormalTok{t }\OtherTok{\textless{}{-}}\NormalTok{ ds}\SpecialCharTok{$}\NormalTok{Cohens\_d}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(m}\SpecialCharTok{*}\NormalTok{n}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{+}\NormalTok{n)) }\CommentTok{\# t値}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ m}\SpecialCharTok{+}\NormalTok{n}\DecValTok{{-}2} \CommentTok{\# 自由度}
\FunctionTok{library}\NormalTok{(MBESS)}
\NormalTok{lambda.ci }\OtherTok{\textless{}{-}} \FunctionTok{conf.limits.nct}\NormalTok{(}\AttributeTok{t.value=}\NormalTok{t, }\AttributeTok{df=}\NormalTok{df, }\AttributeTok{conf.level =}\NormalTok{ .}\DecValTok{95}\NormalTok{) }\CommentTok{\# 非心t分布の95\%点}
\NormalTok{lambda.ci}\SpecialCharTok{$}\NormalTok{Lower.Limit}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{((m}\SpecialCharTok{+}\NormalTok{n)}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{*}\NormalTok{n))  }\CommentTok{\# 95\%信頼区間の下限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.968447
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lambda.ci}\SpecialCharTok{$}\NormalTok{Upper.Limit}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{((m}\SpecialCharTok{+}\NormalTok{n)}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{*}\NormalTok{n))  }\CommentTok{\# 95\%信頼区間の上限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.576903
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{cohens\_d}\NormalTok{(A, B)  }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 1.27      | [0.97, 1.58]
## 
## - Estimated using pooled SD.
\end{verbatim}

ただし、この方法ではGlassの \(\Delta\) の信頼区間を求めることができない（等分散の場合を除く）。その場合、次に示すブートストラップ法を用いる。

\hypertarget{ux30d6ux30fcux30c8ux30b9ux30c8ux30e9ux30c3ux30d7ux6cd5}{%
\subsubsection{ブートストラップ法}\label{ux30d6ux30fcux30c8ux30b9ux30c8ux30e9ux30c3ux30d7ux6cd5}}

3つ目は、ブートストラップ法を用いる方法である。ブートストラップ法とは、標本からの復元抽出を繰り返すことで大きな標本を生成し、そこから得られる近似分布（経験分布）によって標準誤差や信頼区間を求める方法である。ブートストラップ法では、母集団分布を仮定せずに信頼区間を計算することができるため便利である。

ここでは既存のパッケージを利用して、Cohen's \(d_s\) の95\%信頼区間を求める。R=10000回の復元抽出を行うよう設定している。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{score=}\FunctionTok{append}\NormalTok{(A, B), }\AttributeTok{group=}\FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{, }\StringTok{"B"}\NormalTok{), }\AttributeTok{each=}\DecValTok{100}\NormalTok{))}
\FunctionTok{library}\NormalTok{(bootES)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\FunctionTok{bootES}\NormalTok{(}\AttributeTok{data =}\NormalTok{ dat, }\AttributeTok{data.col =} \StringTok{"score"}\NormalTok{, }\AttributeTok{group.col =} \StringTok{"group"}\NormalTok{, }\AttributeTok{contrast =} \FunctionTok{c}\NormalTok{(}\StringTok{"B"}\NormalTok{,}\StringTok{"A"}\NormalTok{), }
       \AttributeTok{effect.type =} \StringTok{"cohens.d"}\NormalTok{, }\AttributeTok{ci.conf =} \FloatTok{0.95}\NormalTok{, }\AttributeTok{R =} \DecValTok{10000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## User-specified lambdas: (B, A)
## Scaled lambdas: (-1, 1)
## 95.00% bca Confidence Interval, 10000 replicates
## Stat        CI (Low)    CI (High)   bias        SE          
## 1.274       0.931       1.602       0.014       0.172
\end{verbatim}

Glassの \(\Delta\) の95\%信頼区間も以下のように求められる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{score=}\FunctionTok{append}\NormalTok{(A, B), }\AttributeTok{group=}\FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{, }\StringTok{"B"}\NormalTok{), }\AttributeTok{each=}\DecValTok{100}\NormalTok{))}
\FunctionTok{library}\NormalTok{(bootES)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\FunctionTok{bootES}\NormalTok{(}\AttributeTok{data =}\NormalTok{ dat, }\AttributeTok{data.col =} \StringTok{"score"}\NormalTok{, }\AttributeTok{group.col =} \StringTok{"group"}\NormalTok{, }\AttributeTok{contrast =} \FunctionTok{c}\NormalTok{(}\StringTok{"B"}\NormalTok{,}\StringTok{"A"}\NormalTok{), }
       \AttributeTok{effect.type =} \StringTok{"cohens.d"}\NormalTok{, }\AttributeTok{glass.control =} \StringTok{"B"}\NormalTok{, }\AttributeTok{ci.conf =} \FloatTok{0.95}\NormalTok{, }\AttributeTok{R =} \DecValTok{10000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## User-specified lambdas: (B, A)
## Scaled lambdas: (-1, 1)
## 95.00% bca Confidence Interval, 10000 replicates
## Stat        CI (Low)    CI (High)   bias        SE          
## 1.239       0.856       1.612       0.023       0.196
\end{verbatim}

\hypertarget{ux30d9ux30a4ux30baux7d71ux8a08ux306bux57faux3065ux304fux30a2ux30d7ux30edux30fcux30c1-1}{%
\subsection{ベイズ統計に基づくアプローチ}\label{ux30d9ux30a4ux30baux7d71ux8a08ux306bux57faux3065ux304fux30a2ux30d7ux30edux30fcux30c1-1}}

ベイズ統計に基づき、母効果量とその信用区間について推論する方法を紹介する。なお、ここでの説明は、\url{https://sucre-stat.com/2021/06/bayesian-hypothesis-testing-2theory/} を参考にした。

いま、2つの独立した母集団A, Bから抽出した2標本がそれぞれ以下のように正規分布に従うとする。ここでは、それぞれの正規分布の平均が2群に共通した母平均 \(\mu\) からどれだけ離れているかを母効果量パラメータ \(\delta\) を組み込んで表現している。また、群間で分散は共通であると仮定している。

\[
\begin{cases}
A_i \sim \mathcal{N}\left(\mu - \cfrac{\delta \sigma}{2}, \sigma^2\right),~~~i=1,\ldots,m \\
B_j \sim \mathcal{N}\left(\mu + \cfrac{\delta \sigma}{2}, \sigma^2\right),~~~j=1,\ldots,n
\end{cases} 
\]

各パラメータの事前分布を以下のように設定する。これは、Jeffreys-Zellner-Siow（JZS）の事前分布と呼ばれるジェフリーズ事前分布の一種である。今回は、\(r=1/\sqrt{2}\) とする。

\[
\begin{cases}
\delta \sim \mathrm{Cauchy}(0,r) \\
\pi\left(\sigma^2\right) ∝ \cfrac{1}{\sigma^2} \\
\pi\left(\mu\right) ∝ 1
\end{cases}
\]

JZSの事前分布を用いた場合の母効果量 \(\delta\) の事後分布の式については割愛するが、以下のRコードでのMAP推定値と信用区間を求めることができる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{)}

\FunctionTok{library}\NormalTok{(BayesFactor)}
\NormalTok{bf }\OtherTok{\textless{}{-}} \FunctionTok{ttestBF}\NormalTok{(A, B, }\AttributeTok{paired =}\NormalTok{ F) }\CommentTok{\# ベイズファクター BF\_10}
\FunctionTok{library}\NormalTok{(bayestestR)}
\FunctionTok{describe\_prior}\NormalTok{(bf) }\CommentTok{\# 事前分布}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Parameter Prior_Distribution Prior_Location Prior_Scale
## 1 Difference             cauchy              0   0.7071068
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{effectsize}\NormalTok{(bf, }\AttributeTok{test =} \ConstantTok{NULL}\NormalTok{) }\CommentTok{\# 事後分布における効果量のMAP推定値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 1.25      | [0.94, 1.56]
\end{verbatim}

\hypertarget{ux7d50ux679cux306eux5831ux544a-1}{%
\subsection{結果の報告}\label{ux7d50ux679cux306eux5831ux544a-1}}

標準化平均値差を報告する際には、以下の4点を報告すればよい。

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  効果の方向（2つの集団のどちらからどちらを引いたか。値が正の場合はどちらの集団が大きいことになるか。）
\item
  効果量の種類（\(d, d_S, \Delta\) など）
\item
  効果量の点推定値
\item
  推定の不確実性（95\%信頼区間など）
\end{enumerate}

Rを用いて以下のように結果報告の表や文章を出力することもできる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{)}

\FunctionTok{library}\NormalTok{(report)}
\FunctionTok{report\_table}\NormalTok{(}\FunctionTok{t.test}\NormalTok{(A, B, }\AttributeTok{var.equal =}\NormalTok{ T)) }\CommentTok{\# 表}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parameter1 | Parameter2 | Mean_Parameter1 | Mean_Parameter2 | Difference |        95% CI | t(198) |      p |            Method | Alternative | Cohen's d | Cohens_d  CI
## -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
## A          |          B |           60.90 |           48.92 |      11.98 | [9.36, 14.60] |   9.01 | < .001 | Two Sample t-test |   two.sided |      1.27 | [0.97, 1.58]
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{report}\NormalTok{(}\FunctionTok{t.test}\NormalTok{(A, B, }\AttributeTok{var.equal =}\NormalTok{ T)) }\CommentTok{\# 文章}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Effect sizes were labelled following Cohen's (1988) recommendations.
## 
## The Two Sample t-test testing the difference between A and B (mean of x = 60.90, mean of y = 48.92) suggests that the effect is positive, statistically significant, and large (difference = 11.98, 95% CI [9.36, 14.60], t(198) = 9.01, p < .001; Cohen's d = 1.27, 95% CI [0.97, 1.58])
\end{verbatim}

\hypertarget{ux5bfeux5fdcux306eux3042ux308b2ux7fa4ux306eux5e73ux5747ux5024ux5dee}{%
\section{対応のある2群の平均値差}\label{ux5bfeux5fdcux306eux3042ux308b2ux7fa4ux306eux5e73ux5747ux5024ux5dee}}

同一集団に対する2回の測定を行う状況を考える（プレ・ポストデザイン）。いま、下記の二変量正規分布に独立に従うn=100の2組（プレ・ポスト）の標本を得たとする。これは、プレの母平均が50、母分散が100、ポストの母平均が60、母分散が100、プレ・ポストの母相関が0.5であることを意味している。

\[
\begin{pmatrix} X_{pre} \\ X_{post} \end{pmatrix} \sim MultiNormal \left( \boldsymbol{\mu}, \boldsymbol{\Sigma} \right),\\
\boldsymbol{\mu} = \begin{pmatrix} 50 \\ 60 \end{pmatrix}, 
\boldsymbol{\Sigma} = \begin{pmatrix} 100 & 50 \\ 
50 & 100 \end{pmatrix}\\
\]

2つの測定値の差も正規分布に従う。

\[
X_{post}-X_{pre}\sim Normal(10, 100)
\]

Rを使って上記の分布に従う乱数を発生させてみよう。このデータを用いて後に示す効果量を計算していく。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(mvtnorm)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{sigma }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{100}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{100}\NormalTok{), }\AttributeTok{byrow=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{ncol=}\DecValTok{2}\NormalTok{) }
\NormalTok{mu }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{50}\NormalTok{, }\DecValTok{60}\NormalTok{)}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{100}
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\FunctionTok{rmvnorm}\NormalTok{(}\AttributeTok{n=}\NormalTok{n, }\AttributeTok{mean=}\NormalTok{mu, }\AttributeTok{sigma=}\NormalTok{sigma)) }
\FunctionTok{colnames}\NormalTok{(dat) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"pre"}\NormalTok{,}\StringTok{"post"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux975eux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee-1}{%
\subsection{非標準化平均値差}\label{ux975eux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee-1}}

プレ・ポストの平均値差Dは、以下の式で求められる。これは非標準化効果量の一種であり、元の測定単位における比較に関心がある場合などに有用である。 \[
D=\bar{x}_{post}-\bar{x}_{pre}
\] 誤差分散は以下の式で求められる。\(\hat\sigma^2_{pre}\) はプレの標準偏差、\(\hat\sigma^2_{post}\) はポストの標準偏差、\(r\) はプレとポストの相関係数を指す。 \[
V_D=\frac{\hat\sigma^2_{pre}+\hat\sigma^2_{post}-(2r*\hat\sigma^2_{pre}*\hat\sigma^2_{post})}{n}
\]

\hypertarget{ux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee-1}{%
\subsection{標準化平均値差}\label{ux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee-1}}

対応のある2群の平均値差の標準化効果量として、対応の無い場合の標準化効果量を用いる方法もある。しかしながら、これはプレ・ポストの相関を考慮しておらず、相関の大きさに関係なく常に一定の値になる。これは対応のあるｔ検定の結果とも対応しないことからやや不自然である。

そこで、相関を考慮した効果量として新たに以下のような母効果量を定義する(\protect\hyperlink{ref-kline2004}{Kline, 2004, p. 106})。ここで、\(\mu_{D}\) はプレ・ポストの差の期待値、\(σ_D\) はプレ・ポストの平均値差の母標準偏差、 \(σ\) はプレ・ポストで共通な母標準偏差である。

\[
\delta_p=\frac{\mu_{D}}{\sigma_D}=\frac{\mu_{D}}{\sigma\sqrt{2(1-\rho)}}
\] \(\delta\) と \(\delta_p\) では分母の計算式が異なる。 \(\delta_p\) の場合、プレ・ポストの相関を含む平方根が新たに加わっている。式から分かる通り、同じ平均値差の場合、相関が大きくなるほど効果量も大きくなる。相関が大きいことは言い換えれば平均値差の標準偏差が小さいことを意味する。

また、相関の絶対値が0.5のとき、\(\delta\) と \(\delta_p\) は一致する。\(\delta_p\) に \(\sqrt{2(1-\rho)}\) をかければ \(\delta\) に変換できる。

\hypertarget{cohens-d_z}{%
\subsubsection{\texorpdfstring{Cohen's \(d_z\)}{Cohen's d\_z}}\label{cohens-d_z}}

母効果量 \(\delta_p\) の推定量である標本効果量としては、Cohen の \(d_z\) がある。 これは、プレ・ポストの平均値差を平均値差の標準偏差で割ることで得られる(\protect\hyperlink{ref-cohen1988}{Cohen, 1988, p. 48})。ここで、\(\hat\sigma_D\) は平均値差の標準偏差、\(\hat\sigma_A^2\) は群Aの不偏分散、\(\hat\sigma_B^2\) は群Bの不偏分差を指す。zという添え字は、Cohen (\protect\hyperlink{ref-cohen1988}{1988}) がXとYの差をZと表現したことに由来する。 \[
D=\bar{x}_{post}-\bar{x}_{pre}\\
Cohen's~d_z=\frac{D}{\hat\sigma_D}=\frac{D}{\sqrt{\hat\sigma_{pre}^2+\hat\sigma_{post}^2-2*cov(x_{pre}, x_{post})}}
\] 誤差分散は以下の式で求められる。ここで、\(r\) は、プレとポストの相関係数を指す。

\[
V_{d_z} = \dfrac{2(1-r)}{n}+\frac{d_z^2}{2n}
\]

Rを利用すれば、Cohen の \(d_z\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post}\SpecialCharTok{{-}}\NormalTok{dat}\SpecialCharTok{$}\NormalTok{pre)}\SpecialCharTok{/}\FunctionTok{sd}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post}\SpecialCharTok{{-}}\NormalTok{dat}\SpecialCharTok{$}\NormalTok{pre)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9587383
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{cohens\_d}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post, dat}\SpecialCharTok{$}\NormalTok{pre, }\AttributeTok{paired =}\NormalTok{ T) }\CommentTok{\# Cohen\textquotesingle{}s d\_z}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 0.96      | [0.72, 1.20]
\end{verbatim}

\hypertarget{ux4fe1ux983cux533aux9593-1}{%
\subsection{信頼区間}\label{ux4fe1ux983cux533aux9593-1}}

対応のある2群の平均値差の効果量の信頼区間の計算についても、独立した2群の場合と同様の3種類の方法が使用できる。ここでは、非心ｔ分布に基づく方法のみ紹介する。これは、以下の式で計算される検定統計量ｔが帰無仮説が偽のときに、非心度\(λ\)、自由度\(df\)の非心ｔ分布に従うことを利用する方法である。

\[
t=d_z*\sqrt{n},\\
\lambda=\delta*\sqrt{n},\\
df=n-1
\]
今回の例の場合、自由度\(df=99\)の非心ｔ分布を非心度\(λ\)を変えながら描いていったとき、検定統計量\(t\)の実現値\(t=9.587383\)が上側確率0.975に一致する非心度\(λ_L\)を求める。そして、それに\(\sqrt{n}\)をかけることで効果量\(\delta\)に変換したものが効果量\(d_s\)の信頼区間の上限値になる。同様に、検定統計量\(t\)の実現値が非心ｔ分布の下側確率0.025に一致する非心度\(λ_H\)を求めて変換すれば効果量\(d_s\)の信頼区間の下限値になる。非心ｔ分布の詳細については、(\protect\hyperlink{ref-haebara2014}{南風原朝和, 2014})などを参照されたい。

Rを利用すれば、Cohen's \(d_s\) の95\%信頼区間は以下のように求められる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{dz }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post, dat}\SpecialCharTok{$}\NormalTok{pre, }\AttributeTok{paired =}\NormalTok{ T) }\CommentTok{\# Cohen\textquotesingle{}s d\_z}
\NormalTok{t }\OtherTok{\textless{}{-}}\NormalTok{ dz}\SpecialCharTok{$}\NormalTok{Cohens\_d}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(n) }\CommentTok{\# t値}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ n}\DecValTok{{-}1} \CommentTok{\# 自由度}
\FunctionTok{library}\NormalTok{(MBESS)}
\NormalTok{lambda.ci }\OtherTok{\textless{}{-}} \FunctionTok{conf.limits.nct}\NormalTok{(}\AttributeTok{t.value =}\NormalTok{ t, }\AttributeTok{df=}\NormalTok{df, }\AttributeTok{conf.level =}\NormalTok{ .}\DecValTok{95}\NormalTok{) }\CommentTok{\# 非心t分布の95\%点}
\NormalTok{lambda.ci}\SpecialCharTok{$}\NormalTok{Lower.Limit}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)  }\CommentTok{\# 95\%信頼区間の下限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.719982
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lambda.ci}\SpecialCharTok{$}\NormalTok{Upper.Limit}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)  }\CommentTok{\# 95\%信頼区間の上限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.194118
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{cohens\_d}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post, dat}\SpecialCharTok{$}\NormalTok{pre, }\AttributeTok{paired =}\NormalTok{ T) }\CommentTok{\# Cohen\textquotesingle{}s d\_z}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 0.96      | [0.72, 1.20]
\end{verbatim}

\hypertarget{ux7d50ux679cux306eux5831ux544a-2}{%
\subsection{結果の報告}\label{ux7d50ux679cux306eux5831ux544a-2}}

対応のある2群の標準化平均値差を報告する際には、以下の5点を報告すればよい。

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  効果の方向（値が正の場合はプレとポストのどちらが大きいことになるか。）
\item
  効果量の種類（\(d_z\) など）
\item
  効果量の点推定値
\item
  推定の不確実性（95\%信頼区間など）
\item
  プレとポストの相関係数r
\end{enumerate}

Rを用いて以下のように結果報告の表や文章を出力することもできる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(report)}
\FunctionTok{report\_table}\NormalTok{(}\FunctionTok{t.test}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post, dat}\SpecialCharTok{$}\NormalTok{pre, }\AttributeTok{paired =}\NormalTok{ T)) }\CommentTok{\# 表}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parameter |   Group | Difference | t(99) |      p |        95% CI |        Method | Alternative | Cohen's d | Cohens_d  CI
## --------------------------------------------------------------------------------------------------------------------------
## dat$post  | dat$pre |       9.80 |  9.59 | < .001 | [7.77, 11.82] | Paired t-test |   two.sided |      0.96 | [0.72, 1.20]
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{report}\NormalTok{(}\FunctionTok{t.test}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post, dat}\SpecialCharTok{$}\NormalTok{pre, }\AttributeTok{paired =}\NormalTok{ T)) }\CommentTok{\# 文章}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Effect sizes were labelled following Cohen's (1988) recommendations.
## 
## The Paired t-test testing the difference between dat$post and dat$pre (mean difference = 9.80) suggests that the effect is positive, statistically significant, and large (difference = 9.80, 95% CI [7.77, 11.82], t(99) = 9.59, p < .001; Cohen's d = 0.96, 95% CI [0.72, 1.20])
\end{verbatim}

\hypertarget{ux6a19ux6e96ux5316ux5e73ux5747ux5024ux5deeux306eux88dcux6b63}{%
\section{標準化平均値差の補正}\label{ux6a19ux6e96ux5316ux5e73ux5747ux5024ux5deeux306eux88dcux6b63}}

標本から得られた統計量を用いて母効果量の推定値を算出する際に特定のバイアスが生じることが予想される場合、バイアスの原因に応じた補正を行うことが考えられる。ここでは、1．小標本の補正、2．信頼性の補正、3．範囲制限の補正を順に紹介する。

\hypertarget{ux5c0fux6a19ux672cux306eux88dcux6b63}{%
\subsection{小標本の補正}\label{ux5c0fux6a19ux672cux306eux88dcux6b63}}

1つ目の補正は小標本の補正である。これまでに紹介した標準化平均値差の効果量には母効果量の推定におけるバイアスが存在し、特に標本が小さい時に顕著である。このバイアスを補正する方法として、標本効果量に以下の補正係数を乗じる方法が提案されている。ここで、\(df\) は自由度を表す。 \[
J\approx1-\frac{3}{4*df-1}
\]

\hypertarget{hedges-g}{%
\subsubsection{\texorpdfstring{Hedges' \(g\)}{Hedges' g}}\label{hedges-g}}

補正係数 \(J\) をCohen's \(d_s\)に乗じることで、バイアスの補正された効果量が得られる。mとnは各群のサンプルサイズである。これは Hedges' \(g\) と呼ばれ、母効果量 \(\delta\) の不偏推定量である(\protect\hyperlink{ref-hedges1981}{Hedges, 1981})。

\[
J\approx1-\frac{3}{4(m+n-2)-1}\\
Heges'~g=J*d_s
\] Rを利用すれば、Hedges の \(g\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(50,100)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)   }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\NormalTok{d}\SpecialCharTok{$}\NormalTok{Cohens\_d }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{3}\SpecialCharTok{/}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{(m}\SpecialCharTok{+}\NormalTok{n}\DecValTok{{-}2}\NormalTok{)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{))) }\CommentTok{\# Hedges\textquotesingle{} g}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.269191
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{hedges\_g}\NormalTok{(A, B)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Hedges' g |       95% CI
## ------------------------
## 1.27      | [0.96, 1.57]
## 
## - Estimated using pooled SD.
\end{verbatim}

\hypertarget{glsss-delta_adj}{%
\subsubsection{\texorpdfstring{Glss's \(\Delta_{adj}\)}{Glss's \textbackslash Delta\_\{adj\}}}\label{glsss-delta_adj}}

補正係数 \(J\) をGlass's \(\Delta\) に乗じることで、バイアスの補正された効果量 Glass's \(\Delta_{adj}\)が得られる(\protect\hyperlink{ref-grissom2005}{Grissom \& Kim, 2005, p. 54})。nは統制群のサンプルサイズである。

\[
J\approx1-\frac{3}{4(n-1)-1}\\
Glass's~\Delta_{adj}=J*\Delta
\]

Rを利用すれば、Glass の \(\Delta_{adj}\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{12}\NormalTok{) }\CommentTok{\# 正規分布N(50,144)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{delta }\OtherTok{\textless{}{-}} \FunctionTok{glass\_delta}\NormalTok{(A, B)  }\CommentTok{\# Glass\textquotesingle{}s delta}
\NormalTok{delta}\SpecialCharTok{$}\NormalTok{Glass\_delta }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{3}\SpecialCharTok{/}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{))) }\CommentTok{\# Glass\textquotesingle{}s delta\_adjusted}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.247999
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{delta }\OtherTok{\textless{}{-}} \FunctionTok{glass\_delta}\NormalTok{(A, B)  }\CommentTok{\# Glass\textquotesingle{}s delta}
\FunctionTok{library}\NormalTok{(psychmeta)}
\FunctionTok{correct\_glass\_bias}\NormalTok{(delta}\SpecialCharTok{$}\NormalTok{Glass\_delta, }\AttributeTok{nc=}\NormalTok{n, }\AttributeTok{ne=}\NormalTok{m)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.247995
\end{verbatim}

\hypertarget{ux30b7ux30dfux30e5ux30ecux30fcux30b7ux30e7ux30f3}{%
\subsubsection{シミュレーション}\label{ux30b7ux30dfux30e5ux30ecux30fcux30b7ux30e7ux30f3}}

これまでに紹介した平均値差の標本効果量が母効果量の推定値としてどのような性質を持つのかをシミュレーションによって確認しよう。以下のコードでは、各効果量について結果格納用の箱を作った上で、任意のサンプルサイズ\(n\)で効果量を算出する計算を10000回繰り返している。母効果量は \(\delta=1\) であることから、バイアスが無ければ10000個の効果量の平均（期待値）と\(\delta=1\)の差は0に近づくはずである（i.e., 不偏性）。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{d }\OtherTok{\textless{}{-}} \ConstantTok{NULL}     \CommentTok{\# Hedged \& Olkin\textquotesingle{}s d の箱}
\NormalTok{ds }\OtherTok{\textless{}{-}} \ConstantTok{NULL}    \CommentTok{\# Cohen\textquotesingle{}s d\_s の箱}
\NormalTok{g }\OtherTok{\textless{}{-}} \ConstantTok{NULL}     \CommentTok{\# Hedges\textquotesingle{}g の箱}
\NormalTok{delta }\OtherTok{\textless{}{-}} \ConstantTok{NULL} \CommentTok{\# Glass\textquotesingle{}s delta の箱}
\NormalTok{delta\_adj }\OtherTok{\textless{}{-}} \ConstantTok{NULL} \CommentTok{\# Glass\textquotesingle{}s delta\_adj の箱}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{5}        \CommentTok{\# サンプルサイズ}
\NormalTok{k }\OtherTok{\textless{}{-}} \DecValTok{10000}    \CommentTok{\# シミュレーション回数}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{k)\{}
\NormalTok{  A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布に従う乱数A}
\NormalTok{  B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布に従う乱数B}
\NormalTok{  svA }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{((A}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(A))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{/}\NormalTok{n }\CommentTok{\# 標本分散A}
\NormalTok{  svB }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{((B}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(B))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{/}\NormalTok{n }\CommentTok{\# 標本分散B}
\NormalTok{  poolsd }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{((n}\SpecialCharTok{*}\NormalTok{svA}\SpecialCharTok{+}\NormalTok{n}\SpecialCharTok{*}\NormalTok{svB)}\SpecialCharTok{/}\NormalTok{(n}\SpecialCharTok{+}\NormalTok{n)) }\CommentTok{\#2群をプールした標準偏差}
\NormalTok{  d[i] }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{mean}\NormalTok{(A)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(B))}\SpecialCharTok{/}\NormalTok{poolsd }\CommentTok{\# Hedged \& Olkin\textquotesingle{}s d}
\NormalTok{  ds[i] }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)}\SpecialCharTok{$}\NormalTok{Cohens\_d }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\NormalTok{  g[i] }\OtherTok{\textless{}{-}} \FunctionTok{hedges\_g}\NormalTok{(A, B)}\SpecialCharTok{$}\NormalTok{Hedges\_g  }\CommentTok{\# Hedges\textquotesingle{}g}
\NormalTok{  delta[i] }\OtherTok{\textless{}{-}} \FunctionTok{glass\_delta}\NormalTok{(A, B)}\SpecialCharTok{$}\NormalTok{Glass\_delta    }\CommentTok{\# Glass\textquotesingle{}s delta}
\NormalTok{  delta\_adj[i] }\OtherTok{\textless{}{-}}\NormalTok{ delta[i]}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{3}\SpecialCharTok{/}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{))) }\CommentTok{\# Glass\textquotesingle{}s delta\_adj}
\NormalTok{\}}
\CommentTok{\# bias}
\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(d)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{)}
\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(ds)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{) ; }\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(g)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{)}
\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(delta)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{) ; }\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(delta\_adj)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\(n\) の値を変えながらK=10000回のシミュレーションを繰り返すと、以下のような結果が得られる。

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1757}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1081}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1216}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1216}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1081}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1216}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1216}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1216}}@{}}
\caption{標準化平均値差の効果量のバイアス}\tabularnewline
\toprule
\begin{minipage}[b]{\linewidth}\raggedright
EStype \textbackslash{} n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
5
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
10
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
20
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
30
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
100
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
1000
\end{minipage} \\
\midrule
\endfirsthead
\toprule
\begin{minipage}[b]{\linewidth}\raggedright
EStype \textbackslash{} n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
5
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
10
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
20
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
30
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
100
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
1000
\end{minipage} \\
\midrule
\endhead
d & 0.2491 & 0.0927 & 0.0431 & 0.0313 & 0.0162 & 0.0069 & 0.0008 \\
d\_s & 0.1172 & 0.0366 & 0.0167 & 0.0140 & 0.0060 & 0.0018 & 0.0003 \\
g & 0.0085 & -0.0073 & -0.0035 & 0.0008 & -0.0018 & -0.002 & -0.0001 \\
delta & 0.2649 & 0.0848 & 0.0382 & 0.0294 & 0.0139 & 0.0056 & -0.0007 \\
delta\_adj & 0.0119 & -0.0082 & -0.0034 & 0.0025 & -0.0016 & -0.0020 & -0.0000 \\
\bottomrule
\end{longtable}

表より、補正係数を使用した\(g\)や\(\Delta_{adj}\)の方が補正係数を使用していない\(d_s\)や\(\Delta\)よりもバイアスが少ない（真値に近い）ことが読み取れる。特に、サンプルサイズが20以下の場合はその差が顕著であり、補正係数を使用した標本効果量の使用が望ましい(\protect\hyperlink{ref-kline2004}{Kline, 2004})。

\hypertarget{ux4fe1ux983cux6027ux306eux88dcux6b63}{%
\subsection{信頼性の補正}\label{ux4fe1ux983cux6027ux306eux88dcux6b63}}

測定の信頼性が低い場合、効果量が少なく見積もられる減衰が問題になる。この問題に対して、測定の信頼性が分かっていればそれに応じた補正を行うことが提案されている(\protect\hyperlink{ref-hunter2004}{Hunter et al., 2004})。 標準化平均値差とその誤差分散については、以下の式で補正する。ここで、\(d_s\) は Cohen の \(d_s\)、\(r_{yy}\) は測定の信頼性を表す。

\[
df=m+n-2, \\
h=\frac{df}{m}+\frac{df}{n},  \\
r_{pb}=\frac{d_s\sqrt{d_s^2+h}}{d_s^2+h}, \\
r_{pb_c}=\frac{r_{pb}}{\sqrt{r_{yy}}},\\
d_c=\frac{r_{pb_c}\sqrt{h}}{\sqrt{1-r_{pb_c}^2}}, \\
V_{d_c}=\frac{V_{d_s}}{r_{yy}}
\]たとえば、標本A, Bに共通した測定の信頼性が0.7であった場合、標準化平均値差は以下のように補正できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(50,100)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\NormalTok{r\_yy }\OtherTok{\textless{}{-}} \FloatTok{0.7}  \CommentTok{\# 信頼性係数}
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)}\SpecialCharTok{$}\NormalTok{Cohens\_d   }\CommentTok{\# Cohen\textquotesingle{}s d\_s}

\NormalTok{df }\OtherTok{=}\NormalTok{ m }\SpecialCharTok{+}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{2}
\NormalTok{h }\OtherTok{=}\NormalTok{ df}\SpecialCharTok{/}\NormalTok{m }\SpecialCharTok{+}\NormalTok{ df}\SpecialCharTok{/}\NormalTok{n}
\NormalTok{rpb }\OtherTok{=}\NormalTok{ (d }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(d}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ h))}\SpecialCharTok{/}\NormalTok{(d}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ h)}
\NormalTok{rpbc }\OtherTok{=}\NormalTok{ rpb}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(r\_yy)}
\NormalTok{dc }\OtherTok{=}\NormalTok{ (rpbc }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(h))}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ rpbc}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{dc}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.677166
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(psychmeta)}
\FunctionTok{correct\_d}\NormalTok{(}\AttributeTok{correction =} \StringTok{"meas"}\NormalTok{, }\AttributeTok{d =}\NormalTok{ d, }\AttributeTok{ryy =}\NormalTok{ r\_yy, }\AttributeTok{n1=}\NormalTok{m, }\AttributeTok{n2=}\NormalTok{n)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## d Values Corrected for Measurement Error:
## ---------------------------------------------------------------------------------------
##   value CI_LL_95 CI_UL_95   n n_effective
## 1  1.68      1.2     2.28 200        96.1
\end{verbatim}

\hypertarget{ux7bc4ux56f2ux5236ux9650ux306eux88dcux6b63}{%
\subsection{範囲制限の補正}\label{ux7bc4ux56f2ux5236ux9650ux306eux88dcux6b63}}

範囲制限とは、母集団を代表しないサブ集団から標本を抽出したことによって、測定変数の範囲が母集団よりも小さくなる状況を指す。例えば、年齢と認知機能の相関を検討する際、65歳から69歳の参加者だけを対象とした調査を行えば、2変数間に強い相関が見られる可能性は極めて低い。なぜなら、参加者の年齢が制限されており、年齢の変動が少ないため、認知能力との相関が検出できないからである。

この問題に対して、範囲が制限されていなかった場合の測定変数の標準偏差が分かれば、範囲制限の補正を行うことができる。制限のない母集団の標準偏差を\(s_p\)、制限された標準偏差を\(s_r\)とすると、補正係数\(U\)は以下の式で求められる。

\[
U=\frac{s_p}{s_r}
\] 補正係数\(U\)を用いて、標準化平均値差\(d_s\)と誤差分散は以下のように補正できる。

\[
df=m+n-2, \\
h=\frac{df}{m}+\frac{df}{n},  \\
r_{pb}=\frac{d_s\sqrt{d_s^2+h}}{d_s^2+h}, \\
r_{pb_c}=\frac{U*r_{pb}}{\sqrt{(U^2-1)r_{pb}^2+1}},\\
d_c=\frac{r_{pb_c}\sqrt{h}}{\sqrt{1-r_{pb_c}^2}}, \\
V_{d_c}=\frac{d_c}{d_s}*V_{d_s}
\]

Rを利用すれば、以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(50,100)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\NormalTok{U }\OtherTok{\textless{}{-}} \FloatTok{1.2}  \CommentTok{\# 標準偏差比}

\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)}\SpecialCharTok{$}\NormalTok{Cohens\_d   }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\NormalTok{df }\OtherTok{=}\NormalTok{ m }\SpecialCharTok{+}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{2}
\NormalTok{h }\OtherTok{=}\NormalTok{ df}\SpecialCharTok{/}\NormalTok{m }\SpecialCharTok{+}\NormalTok{ df}\SpecialCharTok{/}\NormalTok{n}
\NormalTok{rpb }\OtherTok{=}\NormalTok{ (d }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(d}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ h))}\SpecialCharTok{/}\NormalTok{(d}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ h)}
\NormalTok{rpbc }\OtherTok{=}\NormalTok{ U}\SpecialCharTok{*}\NormalTok{rpb}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{((U}\SpecialCharTok{\^{}}\DecValTok{2{-}1}\NormalTok{)}\SpecialCharTok{*}\NormalTok{rpb}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}
\NormalTok{dc }\OtherTok{=}\NormalTok{ (rpbc }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(h))}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ rpbc}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{dc}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.528827
\end{verbatim}

\hypertarget{ux540dux79f0ux306eux6df7ux4e71ux554fux984cux306bux3064ux3044ux3066}{%
\section{名称の混乱問題について}\label{ux540dux79f0ux306eux6df7ux4e71ux554fux984cux306bux3064ux3044ux3066}}

※研究者によって好き勝手な記号を使いすぎ問題。後で加筆。

\begin{figure}
\centering
\includegraphics{images/McGrathMeyer2006.png}
\caption{研究によって異なる記号が使用される. Figure from McGrath \& Meyer (\protect\hyperlink{ref-mcgrath2006}{2006})}
\end{figure}

\hypertarget{ux5e73ux5747ux5024ux5deeux306eux52b9ux679cux91cf-1}{%
\chapter{平均値差の効果量}\label{ux5e73ux5747ux5024ux5deeux306eux52b9ux679cux91cf-1}}

本章では、２群間の平均値差に関する効果量とその信頼区間の計算方法を紹介する。平均値差に関する標準化効果量には複数の種類が存在するが、研究によってそれらの呼び方や使用する記号が異なることがあるので注意が必要である。

\hypertarget{ux72ecux7acbux3057ux305f2ux7fa4ux306eux5e73ux5747ux5024ux5dee-1}{%
\section{独立した2群の平均値差}\label{ux72ecux7acbux3057ux305f2ux7fa4ux306eux5e73ux5747ux5024ux5dee-1}}

2つの独立した母集団A, Bから抽出した2標本の平均値差について検討する。いま、2つの正規母集団 \(\mathcal{N_A}(60, 100), \mathcal{N_B}(50, 100)\) から無作為抽出によって100個ずつ（\(m=100, n=100\)）の独立な標本を得たとする。\[
A_1, A_2, ..., A_{m} \sim \mathcal{N}(60, 100),\\
B_1, B_2, ..., B_{n} \sim \mathcal{N}(50, 100)
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(50,100)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\end{Highlighting}
\end{Shaded}

\includegraphics{book_filename_files/figure-latex/unnamed-chunk-44-1.pdf}

独立した2群の平均値差を示す効果量には、非標準化平均値差と標準化平均値差の2種類がある。また、後者については、等分散が仮定できる場合とできない場合に分けて考えることができる。以下で順に紹介していく。

\hypertarget{ux975eux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee-2}{%
\subsection{非標準化平均値差}\label{ux975eux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee-2}}

2群の平均値差Dは、以下の式で求められる。これは、平均値と同様に非標準化効果量の一種であり、元の測定単位における比較に関心がある場合などに有用である。

\[
平均値差D=\bar{A}-\bar{B}
\] 平均値差Dは、母平均値差 \(\mu_A-\mu_B\) の一致推定量かつ不偏推定量であり、平均\(\mu_A-\mu_B\)、分散 \(\sigma_A^2/m+\sigma_B^2/n\) の正規分布に従う。母分散が既知の場合は、以下のように95\%信頼区間を構成すればよい。

\[
D-1.96\sqrt{\frac{\sigma_A^2}{m}+\frac{\sigma_B^2}{n}}\leq\mu_A-\mu_B\leq D+1.96\sqrt{\frac{\sigma_A^2}{m}+\frac{\sigma_B^2}{n}}
\] Rを利用すれば、以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{D }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(A) }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(B)     }\CommentTok{\# 非標準化平均値差}
\NormalTok{D }\SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{100}\SpecialCharTok{/}\NormalTok{m}\SpecialCharTok{+}\DecValTok{100}\SpecialCharTok{/}\NormalTok{n) }\CommentTok{\# 95\%信頼区間の下限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.207668
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{D }\SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{100}\SpecialCharTok{/}\NormalTok{m}\SpecialCharTok{+}\DecValTok{100}\SpecialCharTok{/}\NormalTok{n) }\CommentTok{\# 95\%信頼区間の上限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 14.75139
\end{verbatim}

母分散が未知であるが集団間で等しいことが分かっている場合、2群に共通した分散を以下の通り求めて、母分散の推定値として利用する。ここで、\(\hat\sigma_A^2\) は群Aの不偏分散、\(\hat\sigma_B^2\) は群Bの不偏分差を指す。 \[
\hat\sigma^2=\frac{(m-1)\hat\sigma_A^2+(n-1)\hat\sigma_B^2}{m+n-2} 
\] 平均値差の標本分布として、正規分布ではなく自由度 \(m+n-2\) のｔ分布を利用して、以下の通り95\%信頼区間を求める。 \[
D-t_{0.025}(m+n-2)\sqrt{\frac{\hat\sigma^2}{m}+\frac{\hat\sigma^2}{n}}\leq\mu_A-\mu_B\leq D+t_{0.975}(m+n-2)\sqrt{\frac{\hat\sigma^2}{m}+\frac{\hat\sigma^2}{n}}
\] Rを利用すれば、以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pooled\_var }\OtherTok{\textless{}{-}}\NormalTok{ ((m}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{var}\NormalTok{(A)}\SpecialCharTok{+}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{var}\NormalTok{(B))}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{+}\NormalTok{n}\DecValTok{{-}2}\NormalTok{)  }\CommentTok{\# 2群に共通した分散の推定値}
\NormalTok{D }\SpecialCharTok{{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.025}\NormalTok{, m}\SpecialCharTok{+}\NormalTok{n}\DecValTok{{-}2}\NormalTok{, }\AttributeTok{lower.tail =}\NormalTok{ F)}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(pooled\_var}\SpecialCharTok{/}\NormalTok{m }\SpecialCharTok{+}\NormalTok{ pooled\_var}\SpecialCharTok{/}\NormalTok{n)  }\CommentTok{\# 95\%信頼区間の下限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.357192
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{D }\SpecialCharTok{+} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, m}\SpecialCharTok{+}\NormalTok{n}\DecValTok{{-}2}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(pooled\_var}\SpecialCharTok{/}\NormalTok{m }\SpecialCharTok{+}\NormalTok{ pooled\_var}\SpecialCharTok{/}\NormalTok{n)                  }\CommentTok{\# 95\%信頼区間の上限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 14.60186
\end{verbatim}

既存の関数を利用して95\%信頼区間を求めても結果は一致する。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(A, B, }\AttributeTok{var.equal =}\NormalTok{ T)}\SpecialCharTok{$}\NormalTok{conf.int}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  9.357192 14.601862
## attr(,"conf.level")
## [1] 0.95
\end{verbatim}

\hypertarget{ux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee-2}{%
\subsection{標準化平均値差}\label{ux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee-2}}

2群の標準化平均値差に関する母効果量\(\delta\)は以下の式で定義される。 \[
\delta=\frac{μ_A-μ_B}{σ}
\]ここで\(μ_A\)，\(μ_B\)はそれぞれ群A, 群Bの母平均、\(σ\)は2群に共通な母標準偏差である。

得られた標本から母効果量\(\delta\)を推定する場合、その推定量を標本効果量と呼ぶ。 標準化平均値差の標本効果量にはいくつかの種類が提案されている。等分散を仮定する場合と等分散を仮定しない場合に分けて順に紹介する。

使用するデータは前節と同様である。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(50,100)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\end{Highlighting}
\end{Shaded}

なお、統計的帰無仮説検定によって2群の平均値差を検討する方法としてはｔ検定が知られており、検定統計量ｔがｔ分布に従うことを利用して、群間で平均値に差が無いという帰無仮説を棄却できるかどうかを判断する。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(A, B, }\AttributeTok{var.equal =}\NormalTok{ T) }\CommentTok{\# 等分散を仮定する場合（Student\textquotesingle{}s t{-}test）}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Two Sample t-test
## 
## data:  A and B
## t = 9.0087, df = 198, p-value < 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   9.357192 14.601862
## sample estimates:
## mean of x mean of y 
##  60.90406  48.92453
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(A, B, }\AttributeTok{var.equal =}\NormalTok{ F) }\CommentTok{\# 等分散を仮定しない場合（Welch\textquotesingle{}s t{-}test）}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  A and B
## t = 9.0087, df = 197.35, p-value < 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   9.357138 14.601916
## sample estimates:
## mean of x mean of y 
##  60.90406  48.92453
\end{verbatim}

\hypertarget{ux7b49ux5206ux6563ux3092ux4eeeux5b9aux3059ux308bux5834ux5408-1}{%
\subsection{等分散を仮定する場合}\label{ux7b49ux5206ux6563ux3092ux4eeeux5b9aux3059ux308bux5834ux5408-1}}

等分散を仮定する場合の標本効果量は主に2種類ある。 これは、2つの集団の分散をどのような計算式で統合（pool）するかの違いである。分散を統合する計算式には、標本分散を用いるものと不偏分散を用いるものがある。

標本分散を用いて統合する場合、以下の式になる。ここで、\(s_A^2\) は群Aの標本分散、\(s_B^2\) は群Bの標本分差を指す。

\[
s_A^2=\frac{1}{m}\sum_{i=1}^{m}(A_i-\bar{A}), s_B^2=\frac{1}{n}\sum_{i=1}^{n}(B_i-\bar{B}), \\
s_{pooled}=\sqrt\frac{ms_A^2+ns_B^2}{m+n}
\] Rを利用すれば、以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Va }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(A)}\SpecialCharTok{*}\NormalTok{(m}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{/}\NormalTok{m  }\CommentTok{\# Aの標本分散}
\NormalTok{Vb }\OtherTok{\textless{}{-}} \FunctionTok{var}\NormalTok{(B)}\SpecialCharTok{*}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{/}\NormalTok{n  }\CommentTok{\# Bの標本分散}
\NormalTok{s\_pooled }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{((m}\SpecialCharTok{*}\NormalTok{Va}\SpecialCharTok{+}\NormalTok{n}\SpecialCharTok{*}\NormalTok{Vb)}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{+}\NormalTok{n))}
\end{Highlighting}
\end{Shaded}

不偏分散を用いて統合する場合、以下の式になる。ここで、\(\hat\sigma_A^2\) は群Aの不偏分散、\(\hat\sigma_B^2\) は群Bの不偏分差を指す。

\[
\hat\sigma_A^2=\frac{1}{m-1}\sum_{i=1}^{m}(A_i-\bar{A}), \hat\sigma_B^2=\frac{1}{n-1}\sum_{i=1}^{n}(B_i-\bar{B}) \\
\hat\sigma=\sqrt\frac{(m-1)\hat\sigma_A^2+(n-1)\hat\sigma_B^2}{m+n-2}
\] Rを利用すれば、以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sigma }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(((m}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{var}\NormalTok{(A)}\SpecialCharTok{+}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\FunctionTok{var}\NormalTok{(B))}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{+}\NormalTok{n}\DecValTok{{-}2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

2種類の推定量の間には、以下のような関係がある。 \[
\hat\sigma=s_{pooled}\sqrt{\frac{m+n}{m+n-2}}
\]

2種類の推定量を用いることでそれぞれ、Hedges \& Olkin の \(d\) とCohenの \(d_s\) という効果量が計算できる。順に紹介していく。

\hypertarget{hedges-olkins-d-1}{%
\subsubsection{\texorpdfstring{Hedges \& Olkin's \(d\)}{Hedges \& Olkin's d}}\label{hedges-olkins-d-1}}

1つ目は、Hedges \& Olkin の \(d\)であり、平均値差を2群に共通した標準偏差（\(s_{pooled}\)）で割ることで得られる。これは、母効果量\(\delta\)の最尤推定量である(\protect\hyperlink{ref-hedges1985}{Hedges \& Olkin, 1985})。この式で計算したものを Cohen's \(d\) と表現している文献もあるので、注意が必要である。

\[
d =\frac{\bar{A}-\bar{B}}{s_{pooled}} 
\]

誤差分散は以下の式で求められる。誤差分散の平方根を求めれば標準誤差になる。

\[
V_d=\frac{m+n}{mn}+\frac{d^2}{2(m+n-2)}
\] Rを利用すれば、Hedges \& Olkin の \(d\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\FunctionTok{mean}\NormalTok{(A)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(B))}\SpecialCharTok{/}\NormalTok{s\_pooled  }\CommentTok{\# Hedges \& Olkin\textquotesingle{}s d}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.280441
\end{verbatim}

\hypertarget{cohens-d_s-2}{%
\subsubsection{\texorpdfstring{Cohen's \(d_s\)}{Cohen's d\_s}}\label{cohens-d_s-2}}

2つ目は、Cohenの \(d_s\) であり、平均値差を2群に共通した標準偏差（\(\hat\sigma\)）で割ることで得られる(\protect\hyperlink{ref-cohen1988}{Cohen, 1988})。この式で計算したものを Cohen's \(d\) や Hedges' \(g\) と表現している文献もあるので、注意が必要である。名称の混乱問題については本章の最後で解説する。

\[
Cohen's~d_s =\frac{\bar{A}-\bar{B}}{\hat\sigma} 
\] 誤差分散は以下の式で求められる。誤差分散の平方根を求めれば標準誤差になる。 \[
V_{d_s}=\frac{m+n}{mn}+\frac {d_s^2}{2(m+n)} 
\] Rを利用すれば、Cohenの \(d_s\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\FunctionTok{mean}\NormalTok{(A)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(B))}\SpecialCharTok{/}\NormalTok{sigma  }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.274023
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{cohens\_d}\NormalTok{(A, B)  }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 1.27      | [0.97, 1.58]
## 
## - Estimated using pooled SD.
\end{verbatim}

\hypertarget{ux7b49ux5206ux6563ux3092ux4eeeux5b9aux3057ux306aux3044ux5834ux5408-1}{%
\subsection{等分散を仮定しない場合}\label{ux7b49ux5206ux6563ux3092ux4eeeux5b9aux3057ux306aux3044ux5834ux5408-1}}

\hypertarget{glasss-delta-1}{%
\subsubsection{\texorpdfstring{Glass's \(\Delta\)}{Glass's \textbackslash Delta}}\label{glasss-delta-1}}

等分散を仮定しない場合の標本効果量としては、Glassの \(\Delta\) がある。 これは、実験デザインに由来して群間で分散が異なることが想定される場合に有用である。 例えば、実験群にのみ介入を行い、その介入が分散を拡大させると考えられる場合、介入を行っていない統制群の分散の推定値を効果量の計算に用いる方が適切だと考えられる(\protect\hyperlink{ref-grissom2001}{Grissom \& Kim, 2001})。Glassの \(\Delta\) はこのような考え方に基づき、2群のうち片方の群の分散（標準偏差）のみを用いて効果量を計算する。

なお、使用するデータは、分散を変更している。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{12}\NormalTok{) }\CommentTok{\# 正規分布N(50,144)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\end{Highlighting}
\end{Shaded}

Glassの \(\Delta\) は以下の計算式の通り、平均値差を片方の群（統制群）の標準偏差で割ることで得られる(\protect\hyperlink{ref-glass1981}{Glass et al., 1981})。ここで、\(\hat\sigma_B^2\) は群Bの不偏分差を指す。ここでは、群Bが統制群であることを想定している。

\[
Glass's~\Delta =\frac{\bar{A}-\bar{B}}{\hat\sigma_B} 
\]

誤差分散は以下の式で求められる(\protect\hyperlink{ref-kline2004}{Kline, 2004, p. 108})。\[
V_{\Delta}=\frac{m+n}{mn}+\frac {\Delta^2}{2(n-1)} 
\] Rを利用すれば、Glassの \(\Delta\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\FunctionTok{mean}\NormalTok{(A)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(B))}\SpecialCharTok{/}\FunctionTok{sd}\NormalTok{(B)  }\CommentTok{\# Glass\textquotesingle{}s delta}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.25755
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{glass\_delta}\NormalTok{(A, B)  }\CommentTok{\# Glass\textquotesingle{}s delta}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Glass' delta |       95% CI
## ---------------------------
## 1.26         | [0.91, 1.60]
\end{verbatim}

\hypertarget{cohens-d_s-3}{%
\subsubsection{\texorpdfstring{Cohen's \(d_s\)}{Cohen's d\_s}}\label{cohens-d_s-3}}

なお、等分散が仮定できるが、分散の推定値に群間で差があった場合は、両群の情報を活用できる \(d\) や \(d_s\) を使用した方がいいだろう(\protect\hyperlink{ref-grissom2001}{Grissom \& Kim, 2001})。例えば、分散の推定値に群間で差があった場合のCohenの \(d_s\) は以下の通り計算することが推奨されている(\protect\hyperlink{ref-delacre2021}{Delacre et al., 2021})。ここで、\(\hat\sigma_A^2\) は群Aの不偏分散、\(\hat\sigma_B^2\) は群Bの不偏分差を指す。

\[
Cohen's~d_s=\frac{\bar{A}-\bar{B}}{\sqrt{(\hat\sigma_A^2+\hat\sigma_B^2)/2}}
\]

Rを利用すれば、分散が異なる場合のCohenの \(d_s\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{(}\FunctionTok{mean}\NormalTok{(A)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(B))}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{((}\FunctionTok{var}\NormalTok{(A)}\SpecialCharTok{+}\FunctionTok{var}\NormalTok{(B))}\SpecialCharTok{/}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.176983
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{cohens\_d}\NormalTok{(A, B, }\AttributeTok{pooled\_sd =}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 1.18      | [0.87, 1.48]
## 
## - Estimated using un-pooled SD.
\end{verbatim}

\hypertarget{ux4fe1ux983cux533aux9593-2}{%
\subsection{信頼区間}\label{ux4fe1ux983cux533aux9593-2}}

標準化平均値差の効果量の信頼区間を算出する方法には、1．標準誤差を用いる方法、2．非心ｔ分布に基づく方法、3．ブートストラップ法の3種類がある(\protect\hyperlink{ref-inoue2008}{井上俊哉, 2008})。以下で順に紹介する。なお、使用するデータは以下の通りである。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(50,100)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux6a19ux6e96ux8aa4ux5deeux3092ux7528ux3044ux308bux65b9ux6cd5-1}{%
\subsubsection{標準誤差を用いる方法}\label{ux6a19ux6e96ux8aa4ux5deeux3092ux7528ux3044ux308bux65b9ux6cd5-1}}

1つ目は、標準誤差 \(se\)（誤差分散\(V_{\hat\delta}\)の平方根）を用いる簡易的な方法である。効果量の標本分布を正規分布で近似することで、95％信頼区間は以下のように計算できる(\protect\hyperlink{ref-nakagawa2007}{Nakagawa \& Cuthill, 2007})。ここで、\(\hat\delta\) は、母効果量 \(\delta\) の推定値である標本効果量（\(d, d_S, \Delta\)）を指す。

\[
\hat{\delta}-1.96*se\leq\delta\leq\hat{\delta}+1.96*se
\]

例えば、Cohen's \(d_s\) の95\%信頼区間は以下のように求められる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{ds }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)  }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\NormalTok{se\_ds }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{((m}\SpecialCharTok{+}\NormalTok{n)}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{*}\NormalTok{n)}\SpecialCharTok{+}\NormalTok{(ds}\SpecialCharTok{$}\NormalTok{Cohens\_d}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\NormalTok{(m}\SpecialCharTok{+}\NormalTok{n))))}
\NormalTok{ds}\SpecialCharTok{$}\NormalTok{Cohens\_d }\SpecialCharTok{{-}} \FloatTok{1.96}\SpecialCharTok{*}\NormalTok{se\_ds  }\CommentTok{\# 95\%信頼区間の下限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9700153
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ds}\SpecialCharTok{$}\NormalTok{Cohens\_d }\SpecialCharTok{+} \FloatTok{1.96}\SpecialCharTok{*}\NormalTok{se\_ds  }\CommentTok{\# 95\%信頼区間の上限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.57803
\end{verbatim}

しかし、これは簡易的な方法であって、正確ではない。より正確な方法としては次の2種類がある。

\hypertarget{ux975eux5fc3uxff54ux5206ux5e03ux306bux57faux3065ux304fux65b9ux6cd5-1}{%
\subsubsection{非心ｔ分布に基づく方法}\label{ux975eux5fc3uxff54ux5206ux5e03ux306bux57faux3065ux304fux65b9ux6cd5-1}}

2つ目は、非心ｔ分布を用いる方法である。これは、以下の式で計算される検定統計量\(t\)が帰無仮説が偽のときに、非心度\(λ\)、自由度\(df\)の非心ｔ分布に従うことを利用する方法である。

\[
t=d_s*\sqrt{\frac{mn}{m+n}},\\
\lambda=\delta*\sqrt{\frac{mn}{m+n}},\\
df=m+n-2
\]

今回の例の場合、自由度\(df=198\)の非心ｔ分布を非心度\(λ\)を変えながら描いていったとき、検定統計量\(t\)の実現値\(t=9.008702\)が上側確率0.975に一致する非心度\(λ_L\)を求める。そして、それに\(\sqrt{\frac{mn}{m+n}}\) をかけることで効果量\(\delta\)に変換したものが効果量\(d_s\)の信頼区間の上限値になる。同様に、検定統計量\(t\)の実現値が非心ｔ分布の下側確率0.025に一致する非心度\(λ_H\)を求めて変換すれば効果量\(d_s\)の信頼区間の下限値になる。非心ｔ分布の詳細については、(\protect\hyperlink{ref-haebara2014}{南風原朝和, 2014})などを参照されたい。※Glass's \(\Delta\) の場合は、自由度\(df\)を\(n-1\)とする。

Rを利用すれば、Cohen's \(d_s\) の95\%信頼区間は以下のように求められる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{ds }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)  }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\NormalTok{t }\OtherTok{\textless{}{-}}\NormalTok{ ds}\SpecialCharTok{$}\NormalTok{Cohens\_d}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(m}\SpecialCharTok{*}\NormalTok{n}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{+}\NormalTok{n)) }\CommentTok{\# t値}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ m}\SpecialCharTok{+}\NormalTok{n}\DecValTok{{-}2} \CommentTok{\# 自由度}
\FunctionTok{library}\NormalTok{(MBESS)}
\NormalTok{lambda.ci }\OtherTok{\textless{}{-}} \FunctionTok{conf.limits.nct}\NormalTok{(}\AttributeTok{t.value=}\NormalTok{t, }\AttributeTok{df=}\NormalTok{df, }\AttributeTok{conf.level =}\NormalTok{ .}\DecValTok{95}\NormalTok{) }\CommentTok{\# 非心t分布の95\%点}
\NormalTok{lambda.ci}\SpecialCharTok{$}\NormalTok{Lower.Limit}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{((m}\SpecialCharTok{+}\NormalTok{n)}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{*}\NormalTok{n))  }\CommentTok{\# 95\%信頼区間の下限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.968447
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lambda.ci}\SpecialCharTok{$}\NormalTok{Upper.Limit}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{((m}\SpecialCharTok{+}\NormalTok{n)}\SpecialCharTok{/}\NormalTok{(m}\SpecialCharTok{*}\NormalTok{n))  }\CommentTok{\# 95\%信頼区間の上限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.576903
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{cohens\_d}\NormalTok{(A, B)  }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 1.27      | [0.97, 1.58]
## 
## - Estimated using pooled SD.
\end{verbatim}

ただし、この方法ではGlassの \(\Delta\) の信頼区間を求めることができない（等分散の場合を除く）。その場合、次に示すブートストラップ法を用いる。

\hypertarget{ux30d6ux30fcux30c8ux30b9ux30c8ux30e9ux30c3ux30d7ux6cd5-1}{%
\subsubsection{ブートストラップ法}\label{ux30d6ux30fcux30c8ux30b9ux30c8ux30e9ux30c3ux30d7ux6cd5-1}}

3つ目は、ブートストラップ法を用いる方法である。ブートストラップ法とは、標本からの復元抽出を繰り返すことで大きな標本を生成し、そこから得られる近似分布（経験分布）によって標準誤差や信頼区間を求める方法である。ブートストラップ法では、母集団分布を仮定せずに信頼区間を計算することができるため便利である。

ここでは既存のパッケージを利用して、Cohen's \(d_s\) の95\%信頼区間を求める。R=10000回の復元抽出を行うよう設定している。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{score=}\FunctionTok{append}\NormalTok{(A, B), }\AttributeTok{group=}\FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{, }\StringTok{"B"}\NormalTok{), }\AttributeTok{each=}\DecValTok{100}\NormalTok{))}
\FunctionTok{library}\NormalTok{(bootES)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\FunctionTok{bootES}\NormalTok{(}\AttributeTok{data =}\NormalTok{ dat, }\AttributeTok{data.col =} \StringTok{"score"}\NormalTok{, }\AttributeTok{group.col =} \StringTok{"group"}\NormalTok{, }\AttributeTok{contrast =} \FunctionTok{c}\NormalTok{(}\StringTok{"B"}\NormalTok{,}\StringTok{"A"}\NormalTok{), }
       \AttributeTok{effect.type =} \StringTok{"cohens.d"}\NormalTok{, }\AttributeTok{ci.conf =} \FloatTok{0.95}\NormalTok{, }\AttributeTok{R =} \DecValTok{10000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## User-specified lambdas: (B, A)
## Scaled lambdas: (-1, 1)
## 95.00% bca Confidence Interval, 10000 replicates
## Stat        CI (Low)    CI (High)   bias        SE          
## 1.274       0.931       1.602       0.014       0.172
\end{verbatim}

Glassの \(\Delta\) の95\%信頼区間も以下のように求められる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{score=}\FunctionTok{append}\NormalTok{(A, B), }\AttributeTok{group=}\FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{, }\StringTok{"B"}\NormalTok{), }\AttributeTok{each=}\DecValTok{100}\NormalTok{))}
\FunctionTok{library}\NormalTok{(bootES)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\FunctionTok{bootES}\NormalTok{(}\AttributeTok{data =}\NormalTok{ dat, }\AttributeTok{data.col =} \StringTok{"score"}\NormalTok{, }\AttributeTok{group.col =} \StringTok{"group"}\NormalTok{, }\AttributeTok{contrast =} \FunctionTok{c}\NormalTok{(}\StringTok{"B"}\NormalTok{,}\StringTok{"A"}\NormalTok{), }
       \AttributeTok{effect.type =} \StringTok{"cohens.d"}\NormalTok{, }\AttributeTok{glass.control =} \StringTok{"B"}\NormalTok{, }\AttributeTok{ci.conf =} \FloatTok{0.95}\NormalTok{, }\AttributeTok{R =} \DecValTok{10000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## User-specified lambdas: (B, A)
## Scaled lambdas: (-1, 1)
## 95.00% bca Confidence Interval, 10000 replicates
## Stat        CI (Low)    CI (High)   bias        SE          
## 1.239       0.856       1.612       0.023       0.196
\end{verbatim}

\hypertarget{ux30d9ux30a4ux30baux7d71ux8a08ux306bux57faux3065ux304fux30a2ux30d7ux30edux30fcux30c1-2}{%
\subsection{ベイズ統計に基づくアプローチ}\label{ux30d9ux30a4ux30baux7d71ux8a08ux306bux57faux3065ux304fux30a2ux30d7ux30edux30fcux30c1-2}}

ベイズ統計に基づき、母効果量とその信用区間について推論する方法を紹介する。なお、ここでの説明は、\url{https://sucre-stat.com/2021/06/bayesian-hypothesis-testing-2theory/} を参考にした。

いま、2つの独立した母集団A, Bから抽出した2標本がそれぞれ以下のように正規分布に従うとする。ここでは、それぞれの正規分布の平均が2群に共通した母平均 \(\mu\) からどれだけ離れているかを母効果量パラメータ \(\delta\) を組み込んで表現している。また、群間で分散は共通であると仮定している。

\[
\begin{cases}
A_i \sim \mathcal{N}\left(\mu - \cfrac{\delta \sigma}{2}, \sigma^2\right),~~~i=1,\ldots,m \\
B_j \sim \mathcal{N}\left(\mu + \cfrac{\delta \sigma}{2}, \sigma^2\right),~~~j=1,\ldots,n
\end{cases} 
\]

各パラメータの事前分布を以下のように設定する。これは、Jeffreys-Zellner-Siow（JZS）の事前分布と呼ばれるジェフリーズ事前分布の一種である。今回は、\(r=1/\sqrt{2}\) とする。

\[
\begin{cases}
\delta \sim \mathrm{Cauchy}(0,r) \\
\pi\left(\sigma^2\right) ∝ \cfrac{1}{\sigma^2} \\
\pi\left(\mu\right) ∝ 1
\end{cases}
\]

JZSの事前分布を用いた場合の母効果量 \(\delta\) の事後分布の式については割愛するが、以下のRコードでのMAP推定値と信用区間を求めることができる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{)}

\FunctionTok{library}\NormalTok{(BayesFactor)}
\NormalTok{bf }\OtherTok{\textless{}{-}} \FunctionTok{ttestBF}\NormalTok{(A, B, }\AttributeTok{paired =}\NormalTok{ F) }\CommentTok{\# ベイズファクター BF\_10}
\FunctionTok{library}\NormalTok{(bayestestR)}
\FunctionTok{describe\_prior}\NormalTok{(bf) }\CommentTok{\# 事前分布}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Parameter Prior_Distribution Prior_Location Prior_Scale
## 1 Difference             cauchy              0   0.7071068
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{effectsize}\NormalTok{(bf, }\AttributeTok{test =} \ConstantTok{NULL}\NormalTok{) }\CommentTok{\# 事後分布における効果量のMAP推定値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 1.25      | [0.94, 1.56]
\end{verbatim}

\hypertarget{ux7d50ux679cux306eux5831ux544a-3}{%
\subsection{結果の報告}\label{ux7d50ux679cux306eux5831ux544a-3}}

標準化平均値差を報告する際には、以下の4点を報告すればよい。

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  効果の方向（2つの集団のどちらからどちらを引いたか。値が正の場合はどちらの集団が大きいことになるか。）
\item
  効果量の種類（\(d, d_S, \Delta\) など）
\item
  効果量の点推定値
\item
  推定の不確実性（95\%信頼区間など）
\end{enumerate}

Rを用いて以下のように結果報告の表や文章を出力することもできる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{)}

\FunctionTok{library}\NormalTok{(report)}
\FunctionTok{report\_table}\NormalTok{(}\FunctionTok{t.test}\NormalTok{(A, B, }\AttributeTok{var.equal =}\NormalTok{ T)) }\CommentTok{\# 表}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parameter1 | Parameter2 | Mean_Parameter1 | Mean_Parameter2 | Difference |        95% CI | t(198) |      p |            Method | Alternative | Cohen's d | Cohens_d  CI
## -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
## A          |          B |           60.90 |           48.92 |      11.98 | [9.36, 14.60] |   9.01 | < .001 | Two Sample t-test |   two.sided |      1.27 | [0.97, 1.58]
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{report}\NormalTok{(}\FunctionTok{t.test}\NormalTok{(A, B, }\AttributeTok{var.equal =}\NormalTok{ T)) }\CommentTok{\# 文章}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Effect sizes were labelled following Cohen's (1988) recommendations.
## 
## The Two Sample t-test testing the difference between A and B (mean of x = 60.90, mean of y = 48.92) suggests that the effect is positive, statistically significant, and large (difference = 11.98, 95% CI [9.36, 14.60], t(198) = 9.01, p < .001; Cohen's d = 1.27, 95% CI [0.97, 1.58])
\end{verbatim}

\hypertarget{ux5bfeux5fdcux306eux3042ux308b2ux7fa4ux306eux5e73ux5747ux5024ux5dee-1}{%
\section{対応のある2群の平均値差}\label{ux5bfeux5fdcux306eux3042ux308b2ux7fa4ux306eux5e73ux5747ux5024ux5dee-1}}

同一集団に対する2回の測定を行う状況を考える（プレ・ポストデザイン）。いま、下記の二変量正規分布に独立に従うn=100の2組（プレ・ポスト）の標本を得たとする。これは、プレの母平均が50、母分散が100、ポストの母平均が60、母分散が100、プレ・ポストの母相関が0.5であることを意味している。

\[
\begin{pmatrix} X_{pre} \\ X_{post} \end{pmatrix} \sim MultiNormal \left( \boldsymbol{\mu}, \boldsymbol{\Sigma} \right),\\
\boldsymbol{\mu} = \begin{pmatrix} 50 \\ 60 \end{pmatrix}, 
\boldsymbol{\Sigma} = \begin{pmatrix} 100 & 50 \\ 
50 & 100 \end{pmatrix}\\
\]

2つの測定値の差も正規分布に従う。

\[
X_{post}-X_{pre}\sim Normal(10, 100)
\]

Rを使って上記の分布に従う乱数を発生させてみよう。このデータを用いて後に示す効果量を計算していく。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(mvtnorm)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{sigma }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{100}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{100}\NormalTok{), }\AttributeTok{byrow=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{ncol=}\DecValTok{2}\NormalTok{) }
\NormalTok{mu }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{50}\NormalTok{, }\DecValTok{60}\NormalTok{)}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{100}
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\FunctionTok{rmvnorm}\NormalTok{(}\AttributeTok{n=}\NormalTok{n, }\AttributeTok{mean=}\NormalTok{mu, }\AttributeTok{sigma=}\NormalTok{sigma)) }
\FunctionTok{colnames}\NormalTok{(dat) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"pre"}\NormalTok{,}\StringTok{"post"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux975eux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee-3}{%
\subsection{非標準化平均値差}\label{ux975eux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee-3}}

プレ・ポストの平均値差Dは、以下の式で求められる。これは非標準化効果量の一種であり、元の測定単位における比較に関心がある場合などに有用である。 \[
D=\bar{x}_{post}-\bar{x}_{pre}
\] 誤差分散は以下の式で求められる。\(\hat\sigma^2_{pre}\) はプレの標準偏差、\(\hat\sigma^2_{post}\) はポストの標準偏差、\(r\) はプレとポストの相関係数を指す。 \[
V_D=\frac{\hat\sigma^2_{pre}+\hat\sigma^2_{post}-(2r*\hat\sigma^2_{pre}*\hat\sigma^2_{post})}{n}
\]

\hypertarget{ux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee-3}{%
\subsection{標準化平均値差}\label{ux6a19ux6e96ux5316ux5e73ux5747ux5024ux5dee-3}}

対応のある2群の平均値差の標準化効果量として、対応の無い場合の標準化効果量を用いる方法もある。しかしながら、これはプレ・ポストの相関を考慮しておらず、相関の大きさに関係なく常に一定の値になる。これは対応のあるｔ検定の結果とも対応しないことからやや不自然である。

そこで、相関を考慮した効果量として新たに以下のような母効果量を定義する(\protect\hyperlink{ref-kline2004}{Kline, 2004, p. 106})。ここで、\(\mu_{D}\) はプレ・ポストの差の期待値、\(σ_D\) はプレ・ポストの平均値差の母標準偏差、 \(σ\) はプレ・ポストで共通な母標準偏差である。

\[
\delta_p=\frac{\mu_{D}}{\sigma_D}=\frac{\mu_{D}}{\sigma\sqrt{2(1-\rho)}}
\] \(\delta\) と \(\delta_p\) では分母の計算式が異なる。 \(\delta_p\) の場合、プレ・ポストの相関を含む平方根が新たに加わっている。式から分かる通り、同じ平均値差の場合、相関が大きくなるほど効果量も大きくなる。相関が大きいことは言い換えれば平均値差の標準偏差が小さいことを意味する。

また、相関の絶対値が0.5のとき、\(\delta\) と \(\delta_p\) は一致する。\(\delta_p\) に \(\sqrt{2(1-\rho)}\) をかければ \(\delta\) に変換できる。

\hypertarget{cohens-d_z-1}{%
\subsubsection{\texorpdfstring{Cohen's \(d_z\)}{Cohen's d\_z}}\label{cohens-d_z-1}}

母効果量 \(\delta_p\) の推定量である標本効果量としては、Cohen の \(d_z\) がある。 これは、プレ・ポストの平均値差を平均値差の標準偏差で割ることで得られる(\protect\hyperlink{ref-cohen1988}{Cohen, 1988, p. 48})。ここで、\(\hat\sigma_D\) は平均値差の標準偏差、\(\hat\sigma_A^2\) は群Aの不偏分散、\(\hat\sigma_B^2\) は群Bの不偏分差を指す。zという添え字は、Cohen (\protect\hyperlink{ref-cohen1988}{1988}) がXとYの差をZと表現したことに由来する。 \[
D=\bar{x}_{post}-\bar{x}_{pre}\\
Cohen's~d_z=\frac{D}{\hat\sigma_D}=\frac{D}{\sqrt{\hat\sigma_{pre}^2+\hat\sigma_{post}^2-2*cov(x_{pre}, x_{post})}}
\] 誤差分散は以下の式で求められる。ここで、\(r\) は、プレとポストの相関係数を指す。

\[
V_{d_z} = \dfrac{2(1-r)}{n}+\frac{d_z^2}{2n}
\]

Rを利用すれば、Cohen の \(d_z\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post}\SpecialCharTok{{-}}\NormalTok{dat}\SpecialCharTok{$}\NormalTok{pre)}\SpecialCharTok{/}\FunctionTok{sd}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post}\SpecialCharTok{{-}}\NormalTok{dat}\SpecialCharTok{$}\NormalTok{pre)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9587383
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{cohens\_d}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post, dat}\SpecialCharTok{$}\NormalTok{pre, }\AttributeTok{paired =}\NormalTok{ T) }\CommentTok{\# Cohen\textquotesingle{}s d\_z}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 0.96      | [0.72, 1.20]
\end{verbatim}

\hypertarget{ux4fe1ux983cux533aux9593-3}{%
\subsection{信頼区間}\label{ux4fe1ux983cux533aux9593-3}}

対応のある2群の平均値差の効果量の信頼区間の計算についても、独立した2群の場合と同様の3種類の方法が使用できる。ここでは、非心ｔ分布に基づく方法のみ紹介する。これは、以下の式で計算される検定統計量ｔが帰無仮説が偽のときに、非心度\(λ\)、自由度\(df\)の非心ｔ分布に従うことを利用する方法である。

\[
t=d_z*\sqrt{n},\\
\lambda=\delta*\sqrt{n},\\
df=n-1
\]
今回の例の場合、自由度\(df=99\)の非心ｔ分布を非心度\(λ\)を変えながら描いていったとき、検定統計量\(t\)の実現値\(t=9.587383\)が上側確率0.975に一致する非心度\(λ_L\)を求める。そして、それに\(\sqrt{n}\)をかけることで効果量\(\delta\)に変換したものが効果量\(d_s\)の信頼区間の上限値になる。同様に、検定統計量\(t\)の実現値が非心ｔ分布の下側確率0.025に一致する非心度\(λ_H\)を求めて変換すれば効果量\(d_s\)の信頼区間の下限値になる。非心ｔ分布の詳細については、(\protect\hyperlink{ref-haebara2014}{南風原朝和, 2014})などを参照されたい。

Rを利用すれば、Cohen's \(d_s\) の95\%信頼区間は以下のように求められる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{dz }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post, dat}\SpecialCharTok{$}\NormalTok{pre, }\AttributeTok{paired =}\NormalTok{ T) }\CommentTok{\# Cohen\textquotesingle{}s d\_z}
\NormalTok{t }\OtherTok{\textless{}{-}}\NormalTok{ dz}\SpecialCharTok{$}\NormalTok{Cohens\_d}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(n) }\CommentTok{\# t値}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ n}\DecValTok{{-}1} \CommentTok{\# 自由度}
\FunctionTok{library}\NormalTok{(MBESS)}
\NormalTok{lambda.ci }\OtherTok{\textless{}{-}} \FunctionTok{conf.limits.nct}\NormalTok{(}\AttributeTok{t.value =}\NormalTok{ t, }\AttributeTok{df=}\NormalTok{df, }\AttributeTok{conf.level =}\NormalTok{ .}\DecValTok{95}\NormalTok{) }\CommentTok{\# 非心t分布の95\%点}
\NormalTok{lambda.ci}\SpecialCharTok{$}\NormalTok{Lower.Limit}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)  }\CommentTok{\# 95\%信頼区間の下限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.719982
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lambda.ci}\SpecialCharTok{$}\NormalTok{Upper.Limit}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(n)  }\CommentTok{\# 95\%信頼区間の上限値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.194118
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{cohens\_d}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post, dat}\SpecialCharTok{$}\NormalTok{pre, }\AttributeTok{paired =}\NormalTok{ T) }\CommentTok{\# Cohen\textquotesingle{}s d\_z}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 0.96      | [0.72, 1.20]
\end{verbatim}

\hypertarget{ux7d50ux679cux306eux5831ux544a-4}{%
\subsection{結果の報告}\label{ux7d50ux679cux306eux5831ux544a-4}}

対応のある2群の標準化平均値差を報告する際には、以下の5点を報告すればよい。

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  効果の方向（値が正の場合はプレとポストのどちらが大きいことになるか。）
\item
  効果量の種類（\(d_z\) など）
\item
  効果量の点推定値
\item
  推定の不確実性（95\%信頼区間など）
\item
  プレとポストの相関係数r
\end{enumerate}

Rを用いて以下のように結果報告の表や文章を出力することもできる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(report)}
\FunctionTok{report\_table}\NormalTok{(}\FunctionTok{t.test}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post, dat}\SpecialCharTok{$}\NormalTok{pre, }\AttributeTok{paired =}\NormalTok{ T)) }\CommentTok{\# 表}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parameter |   Group | Difference | t(99) |      p |        95% CI |        Method | Alternative | Cohen's d | Cohens_d  CI
## --------------------------------------------------------------------------------------------------------------------------
## dat$post  | dat$pre |       9.80 |  9.59 | < .001 | [7.77, 11.82] | Paired t-test |   two.sided |      0.96 | [0.72, 1.20]
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{report}\NormalTok{(}\FunctionTok{t.test}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{post, dat}\SpecialCharTok{$}\NormalTok{pre, }\AttributeTok{paired =}\NormalTok{ T)) }\CommentTok{\# 文章}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Effect sizes were labelled following Cohen's (1988) recommendations.
## 
## The Paired t-test testing the difference between dat$post and dat$pre (mean difference = 9.80) suggests that the effect is positive, statistically significant, and large (difference = 9.80, 95% CI [7.77, 11.82], t(99) = 9.59, p < .001; Cohen's d = 0.96, 95% CI [0.72, 1.20])
\end{verbatim}

\hypertarget{ux6a19ux6e96ux5316ux5e73ux5747ux5024ux5deeux306eux88dcux6b63-1}{%
\section{標準化平均値差の補正}\label{ux6a19ux6e96ux5316ux5e73ux5747ux5024ux5deeux306eux88dcux6b63-1}}

標本から得られた統計量を用いて母効果量の推定値を算出する際に特定のバイアスが生じることが予想される場合、バイアスの原因に応じた補正を行うことが考えられる。ここでは、1．小標本の補正、2．信頼性の補正、3．範囲制限の補正を順に紹介する。

\hypertarget{ux5c0fux6a19ux672cux306eux88dcux6b63-1}{%
\subsection{小標本の補正}\label{ux5c0fux6a19ux672cux306eux88dcux6b63-1}}

1つ目の補正は小標本の補正である。これまでに紹介した標準化平均値差の効果量には母効果量の推定におけるバイアスが存在し、特に標本が小さい時に顕著である。このバイアスを補正する方法として、標本効果量に以下の補正係数を乗じる方法が提案されている。ここで、\(df\) は自由度を表す。 \[
J\approx1-\frac{3}{4*df-1}
\]

\hypertarget{hedges-g-1}{%
\subsubsection{\texorpdfstring{Hedges' \(g\)}{Hedges' g}}\label{hedges-g-1}}

補正係数 \(J\) をCohen's \(d_s\)に乗じることで、バイアスの補正された効果量が得られる。mとnは各群のサンプルサイズである。これは Hedges' \(g\) と呼ばれ、母効果量 \(\delta\) の不偏推定量である(\protect\hyperlink{ref-hedges1981}{Hedges, 1981})。

\[
J\approx1-\frac{3}{4(m+n-2)-1}\\
Heges'~g=J*d_s
\] Rを利用すれば、Hedges の \(g\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(50,100)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)   }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\NormalTok{d}\SpecialCharTok{$}\NormalTok{Cohens\_d }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{3}\SpecialCharTok{/}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{(m}\SpecialCharTok{+}\NormalTok{n}\DecValTok{{-}2}\NormalTok{)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{))) }\CommentTok{\# Hedges\textquotesingle{} g}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.269191
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{hedges\_g}\NormalTok{(A, B)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Hedges' g |       95% CI
## ------------------------
## 1.27      | [0.96, 1.57]
## 
## - Estimated using pooled SD.
\end{verbatim}

\hypertarget{glsss-delta_adj-1}{%
\subsubsection{\texorpdfstring{Glss's \(\Delta_{adj}\)}{Glss's \textbackslash Delta\_\{adj\}}}\label{glsss-delta_adj-1}}

補正係数 \(J\) をGlass's \(\Delta\) に乗じることで、バイアスの補正された効果量 Glass's \(\Delta_{adj}\)が得られる(\protect\hyperlink{ref-grissom2005}{Grissom \& Kim, 2005, p. 54})。nは統制群のサンプルサイズである。

\[
J\approx1-\frac{3}{4(n-1)-1}\\
Glass's~\Delta_{adj}=J*\Delta
\]

Rを利用すれば、Glass の \(\Delta_{adj}\) は以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{12}\NormalTok{) }\CommentTok{\# 正規分布N(50,144)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{delta }\OtherTok{\textless{}{-}} \FunctionTok{glass\_delta}\NormalTok{(A, B)  }\CommentTok{\# Glass\textquotesingle{}s delta}
\NormalTok{delta}\SpecialCharTok{$}\NormalTok{Glass\_delta }\SpecialCharTok{*}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{3}\SpecialCharTok{/}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{))) }\CommentTok{\# Glass\textquotesingle{}s delta\_adjusted}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.247999
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{delta }\OtherTok{\textless{}{-}} \FunctionTok{glass\_delta}\NormalTok{(A, B)  }\CommentTok{\# Glass\textquotesingle{}s delta}
\FunctionTok{library}\NormalTok{(psychmeta)}
\FunctionTok{correct\_glass\_bias}\NormalTok{(delta}\SpecialCharTok{$}\NormalTok{Glass\_delta, }\AttributeTok{nc=}\NormalTok{n, }\AttributeTok{ne=}\NormalTok{m)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.247995
\end{verbatim}

\hypertarget{ux30b7ux30dfux30e5ux30ecux30fcux30b7ux30e7ux30f3-1}{%
\subsubsection{シミュレーション}\label{ux30b7ux30dfux30e5ux30ecux30fcux30b7ux30e7ux30f3-1}}

これまでに紹介した平均値差の標本効果量が母効果量の推定値としてどのような性質を持つのかをシミュレーションによって確認しよう。以下のコードでは、各効果量について結果格納用の箱を作った上で、任意のサンプルサイズ\(n\)で効果量を算出する計算を10000回繰り返している。母効果量は \(\delta=1\) であることから、バイアスが無ければ10000個の効果量の平均（期待値）と\(\delta=1\)の差は0に近づくはずである（i.e., 不偏性）。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{d }\OtherTok{\textless{}{-}} \ConstantTok{NULL}     \CommentTok{\# Hedged \& Olkin\textquotesingle{}s d の箱}
\NormalTok{ds }\OtherTok{\textless{}{-}} \ConstantTok{NULL}    \CommentTok{\# Cohen\textquotesingle{}s d\_s の箱}
\NormalTok{g }\OtherTok{\textless{}{-}} \ConstantTok{NULL}     \CommentTok{\# Hedges\textquotesingle{}g の箱}
\NormalTok{delta }\OtherTok{\textless{}{-}} \ConstantTok{NULL} \CommentTok{\# Glass\textquotesingle{}s delta の箱}
\NormalTok{delta\_adj }\OtherTok{\textless{}{-}} \ConstantTok{NULL} \CommentTok{\# Glass\textquotesingle{}s delta\_adj の箱}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{5}        \CommentTok{\# サンプルサイズ}
\NormalTok{k }\OtherTok{\textless{}{-}} \DecValTok{10000}    \CommentTok{\# シミュレーション回数}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{k)\{}
\NormalTok{  A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布に従う乱数A}
\NormalTok{  B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布に従う乱数B}
\NormalTok{  svA }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{((A}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(A))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{/}\NormalTok{n }\CommentTok{\# 標本分散A}
\NormalTok{  svB }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{((B}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(B))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{/}\NormalTok{n }\CommentTok{\# 標本分散B}
\NormalTok{  poolsd }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{((n}\SpecialCharTok{*}\NormalTok{svA}\SpecialCharTok{+}\NormalTok{n}\SpecialCharTok{*}\NormalTok{svB)}\SpecialCharTok{/}\NormalTok{(n}\SpecialCharTok{+}\NormalTok{n)) }\CommentTok{\#2群をプールした標準偏差}
\NormalTok{  d[i] }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{mean}\NormalTok{(A)}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(B))}\SpecialCharTok{/}\NormalTok{poolsd }\CommentTok{\# Hedged \& Olkin\textquotesingle{}s d}
\NormalTok{  ds[i] }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)}\SpecialCharTok{$}\NormalTok{Cohens\_d }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\NormalTok{  g[i] }\OtherTok{\textless{}{-}} \FunctionTok{hedges\_g}\NormalTok{(A, B)}\SpecialCharTok{$}\NormalTok{Hedges\_g  }\CommentTok{\# Hedges\textquotesingle{}g}
\NormalTok{  delta[i] }\OtherTok{\textless{}{-}} \FunctionTok{glass\_delta}\NormalTok{(A, B)}\SpecialCharTok{$}\NormalTok{Glass\_delta    }\CommentTok{\# Glass\textquotesingle{}s delta}
\NormalTok{  delta\_adj[i] }\OtherTok{\textless{}{-}}\NormalTok{ delta[i]}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{(}\DecValTok{3}\SpecialCharTok{/}\NormalTok{(}\DecValTok{4}\SpecialCharTok{*}\NormalTok{(n}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{))) }\CommentTok{\# Glass\textquotesingle{}s delta\_adj}
\NormalTok{\}}
\CommentTok{\# bias}
\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(d)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{)}
\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(ds)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{) ; }\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(g)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{)}
\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(delta)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{) ; }\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(delta\_adj)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\(n\) の値を変えながらK=10000回のシミュレーションを繰り返すと、以下のような結果が得られる。

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1757}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1081}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1216}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1216}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1081}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1216}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1216}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1216}}@{}}
\caption{標準化平均値差の効果量のバイアス}\tabularnewline
\toprule
\begin{minipage}[b]{\linewidth}\raggedright
EStype \textbackslash{} n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
5
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
10
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
20
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
30
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
100
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
1000
\end{minipage} \\
\midrule
\endfirsthead
\toprule
\begin{minipage}[b]{\linewidth}\raggedright
EStype \textbackslash{} n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
5
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
10
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
20
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
30
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
100
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
1000
\end{minipage} \\
\midrule
\endhead
d & 0.2491 & 0.0927 & 0.0431 & 0.0313 & 0.0162 & 0.0069 & 0.0008 \\
d\_s & 0.1172 & 0.0366 & 0.0167 & 0.0140 & 0.0060 & 0.0018 & 0.0003 \\
g & 0.0085 & -0.0073 & -0.0035 & 0.0008 & -0.0018 & -0.002 & -0.0001 \\
delta & 0.2649 & 0.0848 & 0.0382 & 0.0294 & 0.0139 & 0.0056 & -0.0007 \\
delta\_adj & 0.0119 & -0.0082 & -0.0034 & 0.0025 & -0.0016 & -0.0020 & -0.0000 \\
\bottomrule
\end{longtable}

表より、補正係数を使用した\(g\)や\(\Delta_{adj}\)の方が補正係数を使用していない\(d_s\)や\(\Delta\)よりもバイアスが少ない（真値に近い）ことが読み取れる。特に、サンプルサイズが20以下の場合はその差が顕著であり、補正係数を使用した標本効果量の使用が望ましい(\protect\hyperlink{ref-kline2004}{Kline, 2004})。

\hypertarget{ux4fe1ux983cux6027ux306eux88dcux6b63-1}{%
\subsection{信頼性の補正}\label{ux4fe1ux983cux6027ux306eux88dcux6b63-1}}

測定の信頼性が低い場合、効果量が少なく見積もられる減衰が問題になる。この問題に対して、測定の信頼性が分かっていればそれに応じた補正を行うことが提案されている(\protect\hyperlink{ref-hunter2004}{Hunter et al., 2004})。 標準化平均値差とその誤差分散については、以下の式で補正する。ここで、\(d_s\) は Cohen の \(d_s\)、\(r_{yy}\) は測定の信頼性を表す。

\[
df=m+n-2, \\
h=\frac{df}{m}+\frac{df}{n},  \\
r_{pb}=\frac{d_s\sqrt{d_s^2+h}}{d_s^2+h}, \\
r_{pb_c}=\frac{r_{pb}}{\sqrt{r_{yy}}},\\
d_c=\frac{r_{pb_c}\sqrt{h}}{\sqrt{1-r_{pb_c}^2}}, \\
V_{d_c}=\frac{V_{d_s}}{r_{yy}}
\]たとえば、標本A, Bに共通した測定の信頼性が0.7であった場合、標準化平均値差は以下のように補正できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(50,100)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\NormalTok{r\_yy }\OtherTok{\textless{}{-}} \FloatTok{0.7}  \CommentTok{\# 信頼性係数}
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)}\SpecialCharTok{$}\NormalTok{Cohens\_d   }\CommentTok{\# Cohen\textquotesingle{}s d\_s}

\NormalTok{df }\OtherTok{=}\NormalTok{ m }\SpecialCharTok{+}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{2}
\NormalTok{h }\OtherTok{=}\NormalTok{ df}\SpecialCharTok{/}\NormalTok{m }\SpecialCharTok{+}\NormalTok{ df}\SpecialCharTok{/}\NormalTok{n}
\NormalTok{rpb }\OtherTok{=}\NormalTok{ (d }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(d}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ h))}\SpecialCharTok{/}\NormalTok{(d}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ h)}
\NormalTok{rpbc }\OtherTok{=}\NormalTok{ rpb}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(r\_yy)}
\NormalTok{dc }\OtherTok{=}\NormalTok{ (rpbc }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(h))}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ rpbc}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{dc}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.677166
\end{verbatim}

既存のパッケージを利用した場合でも同様の結果が得られる。

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(psychmeta)}
\FunctionTok{correct\_d}\NormalTok{(}\AttributeTok{correction =} \StringTok{"meas"}\NormalTok{, }\AttributeTok{d =}\NormalTok{ d, }\AttributeTok{ryy =}\NormalTok{ r\_yy, }\AttributeTok{n1=}\NormalTok{m, }\AttributeTok{n2=}\NormalTok{n)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## d Values Corrected for Measurement Error:
## ---------------------------------------------------------------------------------------
##   value CI_LL_95 CI_UL_95   n n_effective
## 1  1.68      1.2     2.28 200        96.1
\end{verbatim}

\hypertarget{ux7bc4ux56f2ux5236ux9650ux306eux88dcux6b63-1}{%
\subsection{範囲制限の補正}\label{ux7bc4ux56f2ux5236ux9650ux306eux88dcux6b63-1}}

範囲制限とは、母集団を代表しないサブ集団から標本を抽出したことによって、測定変数の範囲が母集団よりも小さくなる状況を指す。例えば、年齢と認知機能の相関を検討する際、65歳から69歳の参加者だけを対象とした調査を行えば、2変数間に強い相関が見られる可能性は極めて低い。なぜなら、参加者の年齢が制限されており、年齢の変動が少ないため、認知能力との相関が検出できないからである。

この問題に対して、範囲が制限されていなかった場合の測定変数の標準偏差が分かれば、範囲制限の補正を行うことができる。制限のない母集団の標準偏差を\(s_p\)、制限された標準偏差を\(s_r\)とすると、補正係数\(U\)は以下の式で求められる。

\[
U=\frac{s_p}{s_r}
\] 補正係数\(U\)を用いて、標準化平均値差\(d_s\)と誤差分散は以下のように補正できる。

\[
df=m+n-2, \\
h=\frac{df}{m}+\frac{df}{n},  \\
r_{pb}=\frac{d_s\sqrt{d_s^2+h}}{d_s^2+h}, \\
r_{pb_c}=\frac{U*r_{pb}}{\sqrt{(U^2-1)r_{pb}^2+1}},\\
d_c=\frac{r_{pb_c}\sqrt{h}}{\sqrt{1-r_{pb_c}^2}}, \\
V_{d_c}=\frac{d_c}{d_s}*V_{d_s}
\]

Rを利用すれば、以下のように計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m }\OtherTok{\textless{}{-}} \DecValTok{100}\NormalTok{ ; n }\OtherTok{\textless{}{-}} \DecValTok{100}   \CommentTok{\# サンプルサイズ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)         }\CommentTok{\# 乱数の種の固定}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(m, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(50,100)からm個の乱数を発生}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(n, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{) }\CommentTok{\# 正規分布N(60,100)からn個の乱数を発生}
\NormalTok{U }\OtherTok{\textless{}{-}} \FloatTok{1.2}  \CommentTok{\# 標準偏差比}

\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)}\SpecialCharTok{$}\NormalTok{Cohens\_d   }\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\NormalTok{df }\OtherTok{=}\NormalTok{ m }\SpecialCharTok{+}\NormalTok{ n }\SpecialCharTok{{-}} \DecValTok{2}
\NormalTok{h }\OtherTok{=}\NormalTok{ df}\SpecialCharTok{/}\NormalTok{m }\SpecialCharTok{+}\NormalTok{ df}\SpecialCharTok{/}\NormalTok{n}
\NormalTok{rpb }\OtherTok{=}\NormalTok{ (d }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(d}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ h))}\SpecialCharTok{/}\NormalTok{(d}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ h)}
\NormalTok{rpbc }\OtherTok{=}\NormalTok{ U}\SpecialCharTok{*}\NormalTok{rpb}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{((U}\SpecialCharTok{\^{}}\DecValTok{2{-}1}\NormalTok{)}\SpecialCharTok{*}\NormalTok{rpb}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}
\NormalTok{dc }\OtherTok{=}\NormalTok{ (rpbc }\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(h))}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ rpbc}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{dc}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.528827
\end{verbatim}

\hypertarget{ux540dux79f0ux306eux6df7ux4e71ux554fux984cux306bux3064ux3044ux3066-1}{%
\section{名称の混乱問題について}\label{ux540dux79f0ux306eux6df7ux4e71ux554fux984cux306bux3064ux3044ux3066-1}}

※研究者によって好き勝手な記号を使いすぎ問題。後で加筆。

\begin{figure}
\centering
\includegraphics{images/McGrathMeyer2006.png}
\caption{研究によって異なる記号が使用される. Figure from McGrath \& Meyer (\protect\hyperlink{ref-mcgrath2006}{2006})}
\end{figure}

\hypertarget{ux76f8ux95a2ux306eux52b9ux679cux91cf}{%
\chapter{相関の効果量}\label{ux76f8ux95a2ux306eux52b9ux679cux91cf}}

後で加筆。

\hypertarget{pearsons-r}{%
\subsection{Pearson's r}\label{pearsons-r}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# データ生成}
\FunctionTok{library}\NormalTok{(mvtnorm)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{sigma }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{100}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{100}\NormalTok{), }\AttributeTok{byrow=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{ncol=}\DecValTok{2}\NormalTok{) }
\NormalTok{mu }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{50}\NormalTok{, }\DecValTok{60}\NormalTok{)}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{100}
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\FunctionTok{rmvnorm}\NormalTok{(}\AttributeTok{n=}\NormalTok{n, }\AttributeTok{mean=}\NormalTok{mu, }\AttributeTok{sigma=}\NormalTok{sigma)) }
\FunctionTok{colnames}\NormalTok{(dat) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{,}\StringTok{"B"}\NormalTok{)}

\CommentTok{\# ピアソンの積率相関}
\FunctionTok{library}\NormalTok{(correlation)}
\FunctionTok{correlation}\NormalTok{(dat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # Correlation Matrix (pearson-method)
## 
## Parameter1 | Parameter2 |    r |       95% CI | t(98) |         p
## -----------------------------------------------------------------
## A          |          B | 0.36 | [0.18, 0.52] |  3.87 | < .001***
## 
## p-value adjustment method: Holm (1979)
## Observations: 100
\end{verbatim}

\hypertarget{ux30d9ux30a4ux30ba}{%
\subsection{ベイズ}\label{ux30d9ux30a4ux30ba}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{correlation}\NormalTok{(dat, }\AttributeTok{bayesian =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # Correlation Matrix (pearson-method)
## 
## Parameter1 | Parameter2 |  rho |       95% CI |      pd | % in ROPE |         Prior |        BF
## -----------------------------------------------------------------------------------------------
## A          |          B | 0.34 | [0.18, 0.51] | 100%*** |     0.50% | Beta (3 +- 3) | 162.40***
## 
## Observations: 100
\end{verbatim}

\hypertarget{ux5206ux6563ux306eux52b9ux679cux91cf}{%
\chapter{分散の効果量}\label{ux5206ux6563ux306eux52b9ux679cux91cf}}

後で加筆。

\hypertarget{ux4e00ux5143ux914dux7f6eux5206ux6563ux5206ux6790}{%
\section{一元配置分散分析}\label{ux4e00ux5143ux914dux7f6eux5206ux6563ux5206ux6790}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# data for ANOVA}
\NormalTok{gender }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"M"}\NormalTok{,}\StringTok{"F"}\NormalTok{), }\AttributeTok{times=}\DecValTok{150}\NormalTok{)}
\NormalTok{group }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{,}\StringTok{"B"}\NormalTok{,}\StringTok{"C"}\NormalTok{), }\AttributeTok{each=}\DecValTok{100}\NormalTok{)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{C }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{40}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{gender=}\NormalTok{gender, }\AttributeTok{group=}\NormalTok{group, }\AttributeTok{outcome=}\FunctionTok{c}\NormalTok{(A, B, C))}
\end{Highlighting}
\end{Shaded}

\includegraphics{book_filename_files/figure-latex/unnamed-chunk-85-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# One way ANOVA}
\NormalTok{res1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(outcome }\SpecialCharTok{\textasciitilde{}}\NormalTok{ group, }\AttributeTok{data =}\NormalTok{ dat)}
\FunctionTok{library}\NormalTok{(parameters)}
\FunctionTok{model\_parameters}\NormalTok{(}\FunctionTok{anova}\NormalTok{(res1), }\AttributeTok{eta\_squared=}\StringTok{"raw"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parameter | Sum_Squares |  df | Mean_Square |      F |      p | Eta2
## --------------------------------------------------------------------
## group     |    19705.74 |   2 |     9852.87 | 110.68 | < .001 | 0.43
## Residuals |    26438.60 | 297 |       89.02 |        |        |     
## 
## Anova Table (Type 1 tests)
\end{verbatim}

\hypertarget{ux52b9ux679cux91cf}{%
\subsection{効果量}\label{ux52b9ux679cux91cf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# eta\^{}2}
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{eta\_squared}\NormalTok{(res1, }\AttributeTok{partial =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{alternative =} \StringTok{"two.sided"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # Effect Size for ANOVA (Type I)
## 
## Parameter | Eta2 |       95% CI
## -------------------------------
## group     | 0.43 | [0.35, 0.50]
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FloatTok{19705.74}\SpecialCharTok{/}\NormalTok{(}\FloatTok{19705.74+26438.60}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4270457
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 95\%CI}
\FunctionTok{library}\NormalTok{(MBESS)}
\NormalTok{par }\OtherTok{\textless{}{-}} \FunctionTok{model\_parameters}\NormalTok{(}\FunctionTok{anova}\NormalTok{(res1), }\AttributeTok{eta\_squared=}\StringTok{"raw"}\NormalTok{)}
\NormalTok{lambda.ci }\OtherTok{\textless{}{-}} \FunctionTok{conf.limits.ncf}\NormalTok{(}\AttributeTok{F.value=}\NormalTok{par}\SpecialCharTok{$}\NormalTok{F[}\DecValTok{1}\NormalTok{], }\AttributeTok{df.1 =}\NormalTok{ par}\SpecialCharTok{$}\NormalTok{df[}\DecValTok{1}\NormalTok{], }\AttributeTok{df.2 =}\NormalTok{ par}\SpecialCharTok{$}\NormalTok{df[}\DecValTok{2}\NormalTok{], }\AttributeTok{conf.level =}\NormalTok{ .}\DecValTok{95}\NormalTok{) }\CommentTok{\# 非心F分布}
\NormalTok{lambda.ci}\SpecialCharTok{$}\NormalTok{Lower.Limit}\SpecialCharTok{/}\NormalTok{(}\DecValTok{300}\SpecialCharTok{+}\NormalTok{lambda.ci}\SpecialCharTok{$}\NormalTok{Lower.Limit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3437476
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lambda.ci}\SpecialCharTok{$}\NormalTok{Upper.Limit}\SpecialCharTok{/}\NormalTok{(}\DecValTok{300}\SpecialCharTok{+}\NormalTok{lambda.ci}\SpecialCharTok{$}\NormalTok{Upper.Limit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4945992
\end{verbatim}

\hypertarget{ux4e8cux5143ux914dux7f6eux5206ux6563ux5206ux6790}{%
\section{二元配置分散分析}\label{ux4e8cux5143ux914dux7f6eux5206ux6563ux5206ux6790}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# partial eta\^{}2}
\NormalTok{res2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(outcome }\SpecialCharTok{\textasciitilde{}}\NormalTok{ gender }\SpecialCharTok{+}\NormalTok{ group, }\AttributeTok{data =}\NormalTok{ dat)}
\NormalTok{parameters}\SpecialCharTok{::}\FunctionTok{model\_parameters}\NormalTok{(}\FunctionTok{anova}\NormalTok{(res2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parameter | Sum_Squares |  df | Mean_Square |      F |      p
## -------------------------------------------------------------
## gender    |      120.27 |   1 |      120.27 |   1.35 | 0.246 
## group     |    19705.74 |   2 |     9852.87 | 110.81 | < .001
## Residuals |    26318.33 | 296 |       88.91 |        |       
## 
## Anova Table (Type 1 tests)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{eta\_squared}\NormalTok{(res2, }\AttributeTok{partial =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{alternative =} \StringTok{"two.sided"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # Effect Size for ANOVA (Type I)
## 
## Parameter | Eta2 (partial) |       95% CI
## -----------------------------------------
## gender    |       4.55e-03 | [0.00, 0.03]
## group     |           0.43 | [0.35, 0.50]
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# partial omega\^{}2}
\FunctionTok{omega\_squared}\NormalTok{(res2, }\AttributeTok{partial =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{alternative =} \StringTok{"two.sided"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # Effect Size for ANOVA (Type I)
## 
## Parameter | Omega2 (partial) |       95% CI
## -------------------------------------------
## gender    |         1.17e-03 | [0.00, 0.02]
## group     |             0.42 | [0.34, 0.49]
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{omega\_squared}\NormalTok{(res2, }\AttributeTok{partial =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{alternative =} \StringTok{"two.sided"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{book_filename_files/figure-latex/unnamed-chunk-88-1.pdf}

\hypertarget{ux7d50ux679cux306eux5831ux544a-5}{%
\subsubsection{結果の報告}\label{ux7d50ux679cux306eux5831ux544a-5}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Report}
\FunctionTok{library}\NormalTok{(report)}
\NormalTok{res2 }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(outcome }\SpecialCharTok{\textasciitilde{}}\NormalTok{ gender }\SpecialCharTok{+}\NormalTok{ group, }\AttributeTok{data =}\NormalTok{ dat)}
\FunctionTok{report\_table}\NormalTok{(res2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parameter | Sum_Squares |  df | Mean_Square |      F |      p | Eta2 (partial) | Eta2_partial 95% CI
## ----------------------------------------------------------------------------------------------------
## gender    |      120.27 |   1 |      120.27 |   1.35 | 0.246  |       4.55e-03 |        [0.00, 1.00]
## group     |    19705.74 |   2 |     9852.87 | 110.81 | < .001 |           0.43 |        [0.36, 1.00]
## Residuals |    26318.33 | 296 |       88.91 |        |        |                |
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{report}\NormalTok{(res2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## The ANOVA (formula: outcome ~ gender + group) suggests that:
## 
##   - The main effect of gender is statistically not significant and very small (F(1, 296) = 1.35, p = 0.246; Eta2 (partial) = 4.55e-03, 95% CI [0.00, 1.00])
##   - The main effect of group is statistically significant and large (F(2, 296) = 110.81, p < .001; Eta2 (partial) = 0.43, 95% CI [0.36, 1.00])
## 
## Effect sizes were labelled following Field's (2013) recommendations.
\end{verbatim}

\hypertarget{ux30d9ux30a4ux30ba-1}{%
\subsection{ベイズ}\label{ux30d9ux30a4ux30ba-1}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# For a Bayesian Test }
\NormalTok{gender }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"M"}\NormalTok{,}\StringTok{"F"}\NormalTok{), }\AttributeTok{times=}\DecValTok{150}\NormalTok{)}
\NormalTok{group }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{,}\StringTok{"B"}\NormalTok{,}\StringTok{"C"}\NormalTok{), }\AttributeTok{each=}\DecValTok{100}\NormalTok{)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{C }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{40}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{gender=}\NormalTok{gender, }\AttributeTok{group=}\NormalTok{group, }\AttributeTok{outcome=}\FunctionTok{c}\NormalTok{(A, B, C))}

\FunctionTok{library}\NormalTok{(rstanarm)}
\NormalTok{m\_bayes }\OtherTok{\textless{}{-}} \FunctionTok{stan\_glm}\NormalTok{(outcome }\SpecialCharTok{\textasciitilde{}}\NormalTok{ gender }\SpecialCharTok{+}\NormalTok{ group, }
                    \AttributeTok{data =}\NormalTok{ dat, }\AttributeTok{family =} \FunctionTok{gaussian}\NormalTok{(),}
                    \AttributeTok{refresh =} \DecValTok{0}\NormalTok{)}
\FunctionTok{prior\_summary}\NormalTok{(m\_bayes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Priors for model 'm_bayes' 
## ------
## Intercept (after predictors centered)
##   Specified prior:
##     ~ normal(location = 50, scale = 2.5)
##   Adjusted prior:
##     ~ normal(location = 50, scale = 31)
## 
## Coefficients
##   Specified prior:
##     ~ normal(location = [0,0,0], scale = [2.5,2.5,2.5])
##   Adjusted prior:
##     ~ normal(location = [0,0,0], scale = [62.01,65.77,65.77])
## 
## Auxiliary (sigma)
##   Specified prior:
##     ~ exponential(rate = 1)
##   Adjusted prior:
##     ~ exponential(rate = 0.08)
## ------
## See help('prior_summary.stanreg') for more details
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{pes\_posterior }\OtherTok{\textless{}{-}} \FunctionTok{eta\_squared\_posterior}\NormalTok{(m\_bayes,}
                                       \AttributeTok{draws =} \DecValTok{1000}\NormalTok{, }
                                       \AttributeTok{partial =}\NormalTok{ T) }\CommentTok{\#事後予測分布からのサンプリング}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Simulating effect size... This can take a while...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(bayestestR)}
\FunctionTok{describe\_posterior}\NormalTok{(pes\_posterior, }\AttributeTok{rope\_range =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.1}\NormalTok{), }\AttributeTok{test =} \StringTok{"rope"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Summary of Posterior Distribution
## 
## Parameter |   Median |       95% CI |         ROPE | % in ROPE
## --------------------------------------------------------------
## gender    | 5.46e-03 | [0.00, 0.05] | [0.00, 0.10] |      100%
## group     |     0.43 | [0.32, 0.52] | [0.00, 0.10] |        0%
\end{verbatim}

\hypertarget{ux7d50ux679cux306eux5831ux544a-6}{%
\subsubsection{結果の報告}\label{ux7d50ux679cux306eux5831ux544a-6}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Report}
\FunctionTok{library}\NormalTok{(report)}
\FunctionTok{report\_table}\NormalTok{(m\_bayes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parameter   | Median |           95% CI |     pd | % in ROPE |  Rhat |     ESS |                   Prior | Std. Median | Std_Median 95% CI |      Fit
## -----------------------------------------------------------------------------------------------------------------------------------------------------
## (Intercept) |  60.25 | [ 58.12,  62.35] |   100% |        0% | 1.000 | 3463.00 | Normal (50.34 +- 31.06) |        0.80 |    [ 0.63,  0.97] |         
## genderM     |   1.24 | [ -0.91,   3.37] | 86.85% |    50.21% | 1.000 | 4475.00 |  Normal (0.00 +- 62.01) |        0.10 |    [-0.07,  0.27] |         
## groupB      | -11.95 | [-14.61,  -9.23] |   100% |        0% | 1.000 | 3577.00 |  Normal (0.00 +- 65.77) |       -0.96 |    [-1.18, -0.75] |         
## groupC      | -19.65 | [-22.31, -17.00] |   100% |        0% | 0.999 | 3320.00 |  Normal (0.00 +- 65.77) |       -1.58 |    [-1.79, -1.38] |         
##             |        |                  |        |           |       |         |                         |             |                   |         
## ELPD        |        |                  |        |           |       |         |                         |             |                   | -1101.91
## LOOIC       |        |                  |        |           |       |         |                         |             |                   |  2203.81
## WAIC        |        |                  |        |           |       |         |                         |             |                   |  2203.79
## R2          |        |                  |        |           |       |         |                         |             |                   |     0.43
## R2 (adj.)   |        |                  |        |           |       |         |                         |             |                   |     0.42
## Sigma       |        |                  |        |           |       |         |                         |             |                   |     9.43
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{report}\NormalTok{(m\_bayes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## We fitted a Bayesian linear model (estimated using MCMC sampling with 4 chains of 2000 iterations and a warmup of 1000) to predict outcome with gender and group (formula: outcome ~ gender + group). Priors over parameters were set as normal (mean = 0.00, SD = 62.01), normal (mean = 0.00, SD = 65.77) and normal (mean = 0.00, SD = 65.77) distributions. The model's explanatory power is substantial (R2 = 0.43, 95% CI [0.35, 0.51], adj. R2 = 0.42). The model's intercept, corresponding to gender = F and group = A, is at 60.25 (95% CI [58.12, 62.35]). Within this model:
## 
##   - The effect of gender [M] (Median = 1.24, 95% CI [-0.91, 3.37]) has a 86.85% probability of being positive (> 0), 70.83% of being significant (> 0.62), and 1.05% of being large (> 3.73). The estimation successfully converged (Rhat = 1.000) and the indices are reliable (ESS = 4475)
##   - The effect of group [B] (Median = -11.95, 95% CI [-14.61, -9.23]) has a 100.00% probability of being negative (< 0), 100.00% of being significant (< -0.62), and 100.00% of being large (< -3.73). The estimation successfully converged (Rhat = 1.000) and the indices are reliable (ESS = 3577)
##   - The effect of group [C] (Median = -19.65, 95% CI [-22.31, -17.00]) has a 100.00% probability of being negative (< 0), 100.00% of being significant (< -0.62), and 100.00% of being large (< -3.73). The estimation successfully converged (Rhat = 0.999) and the indices are reliable (ESS = 3320)
## 
## Following the Sequential Effect eXistence and sIgnificance Testing (SEXIT) framework, we report the median of the posterior distribution and its 95% CI (Highest Density Interval), along the probability of direction (pd), the probability of significance and the probability of being large. The thresholds beyond which the effect is considered as significant (i.e., non-negligible) and large are |0.62| and |3.73| (corresponding respectively to 0.05 and 0.30 of the outcome's SD). Convergence and stability of the Bayesian sampling has been assessed using R-hat, which should be below 1.01 (Vehtari et al., 2019), and Effective Sample Size (ESS), which should be greater than 1000 (Burkner, 2017).
\end{verbatim}

\hypertarget{ux6bd4ux7387ux306eux52b9ux679cux91cf}{%
\chapter{比率の効果量}\label{ux6bd4ux7387ux306eux52b9ux679cux91cf}}

後で加筆。

\hypertarget{ux5358ux4e00ux4e8bux4f8bux7814ux7a76ux306eux52b9ux679cux91cf}{%
\chapter{単一事例研究の効果量}\label{ux5358ux4e00ux4e8bux4f8bux7814ux7a76ux306eux52b9ux679cux91cf}}

※日本語で読める優れた解説として、山田剛史 (\protect\hyperlink{ref-ux5c71ux75302020}{2020}) があるのでそちらを参照。

時間があれば \texttt{SingleCaseES} パッケージを利用した計算例を書く予定。

\hypertarget{ux52b9ux679cux91cfux306eux5909ux63db}{%
\chapter{効果量の変換}\label{ux52b9ux679cux91cfux306eux5909ux63db}}

後で加筆。

\hypertarget{ux7d71ux8a08ux91cfux304bux3089ux52b9ux679cux91cfux3078ux306eux5909ux63db}{%
\section{統計量から効果量への変換}\label{ux7d71ux8a08ux91cfux304bux3089ux52b9ux679cux91cfux3078ux306eux5909ux63db}}

\hypertarget{t---d}{%
\subsection{t -\textgreater{} d}\label{t---d}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\CommentTok{\# t to d}
\NormalTok{res.st }\OtherTok{\textless{}{-}} \FunctionTok{t.test}\NormalTok{(A, B)}
\FunctionTok{cohens\_d}\NormalTok{(A, B)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 1.27      | [0.97, 1.58]
## 
## - Estimated using pooled SD.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t\_to\_d}\NormalTok{(res.st}\SpecialCharTok{$}\NormalTok{statistic[}\DecValTok{1}\NormalTok{], res.st}\SpecialCharTok{$}\NormalTok{parameter) }\CommentTok{\#近似値}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## d    |       95% CI
## -------------------
## 1.28 | [0.97, 1.59]
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dhat }\OtherTok{\textless{}{-}} \DecValTok{2}\SpecialCharTok{*}\NormalTok{res.st}\SpecialCharTok{$}\NormalTok{statistic[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(res.st}\SpecialCharTok{$}\NormalTok{parameter)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux52b9ux679cux91cfux304bux3089ux52b9ux679cux91cfux3078ux306eux5909ux63db}{%
\section{効果量から効果量への変換}\label{ux52b9ux679cux91cfux304bux3089ux52b9ux679cux91cfux3078ux306eux5909ux63db}}

\hypertarget{d---r}{%
\subsection{d \textless-\textgreater{} r}\label{d---r}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Converting Between Indices of Effect Size {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# d to r}
\NormalTok{group }\OtherTok{\textless{}{-}} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{), }\AttributeTok{each=}\DecValTok{100}\NormalTok{)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{group=}\NormalTok{group, }\AttributeTok{outcome=}\FunctionTok{c}\NormalTok{(A, B))}

\FunctionTok{cor}\NormalTok{(dat) }\CommentTok{\#点双列相関}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             group   outcome
## group   1.0000000 0.3939704
## outcome 0.3939704 1.0000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{outcome[group}\SpecialCharTok{==}\DecValTok{1}\NormalTok{], dat}\SpecialCharTok{$}\NormalTok{outcome[group}\SpecialCharTok{==}\DecValTok{0}\NormalTok{])}\SpecialCharTok{$}\NormalTok{Cohens\_d}
\NormalTok{r }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(dat}\SpecialCharTok{$}\NormalTok{group, dat}\SpecialCharTok{$}\NormalTok{outcome)}
\NormalTok{d\_convert }\OtherTok{\textless{}{-}} \FunctionTok{r\_to\_d}\NormalTok{(r)}
\NormalTok{r\_convert }\OtherTok{\textless{}{-}} \FunctionTok{d\_to\_r}\NormalTok{(d)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ux52b9ux679cux91cfux306eux89e3ux91c8ux3068ux5229ux7528}{%
\chapter{効果量の解釈と利用}\label{ux52b9ux679cux91cfux306eux89e3ux91c8ux3068ux5229ux7528}}

研究から得られた効果量の値がどのような意味を持つのかを解釈する方法には以下の4つのアプローチがある。

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  共通言語効果量（Common Language Effect Sizes）
\item
  Cohenの規準（一般的なベンチマーク）
\item
  研究分野ごとの基準（分野固有のベンチマーク）
\item
  メタ分析の参照
\end{enumerate}

1つ目は、より解釈しやすい別の指標に変換して解釈する方法である。共通言語効果量と呼ばれる一連の指標を用いて確率的に効果量を解釈することが提案されている(\protect\hyperlink{ref-mcgraw1992}{McGraw \& Wong, 1992})。2つ目は、効果量解釈の目安を示した一般的なベンチマークを参照することである。もっとも有名なベンチマークとしてはCohenによって提案された基準がある。しかし、研究デザインを考慮せずにベンチマークを機械的に当てはめることには多くの批判があり(e.g., \protect\hyperlink{ref-cummings2011}{Cummings, 2011}; \protect\hyperlink{ref-kraft2020}{Kraft, 2020})、何よりもCohen自身がそのような使用法の問題点を認識していた(\protect\hyperlink{ref-cohen1988}{Cohen, 1988, p. 25})。3つ目は、各研究分野で一般的な効果量の大きさを参照するアプローチである。これもCohenの規準と同様の問題を抱えており、分野内でもテーマによって効果量分布が大きく異なることを考慮できていない。4つ目のアプローチは、関連する研究テーマの先行研究を統合したメタ分析の結果を参照する方法である。しかし、メタ分析も出版バイアスや問題のある研究実践（QRPs）の影響によって、効果量の分布を正しくとらえられているとは限らない。このように、効果量の解釈は非常に困難の伴う作業である。

\hypertarget{ux5171ux901aux8a00ux8a9eux52b9ux679cux91cf}{%
\section{共通言語効果量}\label{ux5171ux901aux8a00ux8a9eux52b9ux679cux91cf}}

共通言語効果量とは、効果量（標準化平均値差）を解釈する際の''共通言語''として用いることを意図して提案された指標であり、1．優越率（Probability of Superiority）、2．Cohen's U3、3．被覆度（Overlap）から構成される。※優越率のみを共通言語効果量と呼ぶ文献もある。3つの指標の共通の仮定は、2つの群が等分散の正規分布に従うというものである。 3つの指標を順に解説する。

\hypertarget{ux512aux8d8aux7387probability-of-superiority}{%
\subsection{優越率（Probability of Superiority）}\label{ux512aux8d8aux7387probability-of-superiority}}

優越率とは、一方の群の観測値が他方の群の観測値を上回る確率である(\protect\hyperlink{ref-haebara2014}{南風原朝和, 2014}; \protect\hyperlink{ref-haebara1987}{南風原朝和 \& 芝祐順, 1987})。別の表現をすれば、両群から1個体をランダムサンプリングして比較した場合に、実験群の個体の観測値が統制群を上回る確率である。2つの集団の観測値が等分散の正規分布A, B に独立に従う場合、優越率は以下の式で求められる。ここで、zは標準正規分布の確率点を指す。例えば、\(\delta=1\) の場合、標準正規分布において\(z<\frac{1}{\sqrt{2}}=0.707\) 以下となる確率なので\(\pi_d=0.76\) である。これは、標準化平均値差が \(\delta=1\) の場合、実験群が統制群を上回る確率が76\%であることを意味している。

\[
\pi_d=P(z<\frac{\delta}{\sqrt{2}})
\]

\hypertarget{cohens-u3}{%
\subsection{Cohen's U3}\label{cohens-u3}}

Cohen's U3とは、第1グループ（実験群）の平均値より小さい第2グループ（統制群）の割合である(\protect\hyperlink{ref-cohen1988}{Cohen, 1988})。以下の図で示す通り、標準化平均値差が \(d_s=0.8\) の場合、実験群（水色）の平均（白線）を下回る統制群（紺色）の割合は78.8\%である。Cohen's U3は、統制群の中でどれくらいの割合が実験群の平均に満たない状況にあるのかを理解する上で有用な指標である。

\begin{figure}
\centering
\includegraphics{images/commonl.png}
\caption{共通言語効果量（ds=0.8）}
\end{figure}

\hypertarget{ux88abux8986ux5ea6overlap}{%
\subsection{被覆度（Overlap）}\label{ux88abux8986ux5ea6overlap}}

被覆度は2つの分布の重なる部分の面積であり、上図の黒色で表される部分である。被覆度が大きいほど2群間の差は小さく、\(\delta=0\) のときに被覆度は100\%になる。

以下のサイトで3つの指標の関係を視覚的に確認することができる{[}\url{https://rpsychologist.com/cohend/}{]}。 また、Rを用いて以下のように共通言語効果量を計算できる。

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Common Language Effect Sizes}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\FunctionTok{library}\NormalTok{(effectsize)}
\FunctionTok{cohens\_d}\NormalTok{(A, B)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI
## ------------------------
## 1.27      | [0.97, 1.58]
## 
## - Estimated using pooled SD.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cles}\NormalTok{(A, B)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parameter       | Coefficient |       95% CI
## --------------------------------------------
## Pr(superiority) |        0.82 | [0.75, 0.87]
## Cohen's U3      |        0.90 | [0.83, 0.94]
## Overlap         |        0.52 | [0.43, 0.63]
\end{verbatim}

ここまでの説明で分かる通り、共通言語効果量は効果量を確率で表現しているだけであって、その効果量がどのような意味を持つのかを教えてくれるわけではない。また、実際の母集団分布が正確に等分散の正規分布に従うわけでもない。よって、効果量の意味を解釈する際の参考値としての利用に留めるのが一般的である。

\hypertarget{cohenux306eux898fux6e96}{%
\section{Cohenの規準}\label{cohenux306eux898fux6e96}}

Cohen (\protect\hyperlink{ref-cohen1988}{1988}) は、標準化効果量を解釈する際の目安となる基準を「小（small）」「中（medium）」「大（large）」の3段階で示している。例えば、標準化平均値差については、以下のような目安を提案している(\protect\hyperlink{ref-cohen1988}{Cohen, 1988, pp. 25--27})。

\begin{longtable}[]{@{}cc@{}}
\caption{Cohen の基準 (\protect\hyperlink{ref-cohen1988}{Cohen, 1988})}\tabularnewline
\toprule
d & 判定 \\
\midrule
\endfirsthead
\toprule
d & 判定 \\
\midrule
\endhead
d = 0.2 & Small \\
d = 0.5 & Medium \\
d = 0.8 & Large \\
\bottomrule
\end{longtable}

Cohenの基準は行動科学分野の研究を通してこれまでに得られた効果量を参考にして作成された経験則であり、全ての分野において適応することを意図していたものではなかった。Cohenは、各分野で効果量を解釈するための参照基準がない場合のみ、この基準を参照するという使用法を想定していた(\protect\hyperlink{ref-cohen1988}{Cohen, 1988, p. 25})。しかしながら、本人の意図に反して、Cohenの基準は各分野での適応可能性が十分に吟味されることなく、機械的に使用されることが常態化していった。Lenth (\protect\hyperlink{ref-lenth2001}{2001}) はこの使い方を「定型化効果量（``Canned'' Effect Sizes）」と呼んで批判している。

Cohenの規準に基づいて効果量の大きさがいったん解釈されるとそれ以上の追加の解釈は行われず、効果量の持つ現実的な意味が見失われてしまう。仮に効果量の大きさが小さかったとしても、その発見は現実的に大きな意味を持つものかもしれない(\protect\hyperlink{ref-anvari2021}{Anvari et al., 2021})。例えば、産業分野では小さな効果量であっても、その生産工程の改善が大きな利益につながる可能性がある。疫学の分野では、小さの効果量であっても、多くの命を救うことに貢献する可能性がある。効果量が小さかったとしても、その介入を実施するコストが小さければ、それは実施する価値があるだろう。

また、現実的な意味が見いだしにくい基礎研究においても、効果量が小さいことが当たり前の分野においては、Cohenの基準で「中程度（Medium）」とされる効果量が大きな効果を持つものとして受け入れられるだろう。このように、その分野では大きいとみなされる効果が効果量の大きさそのものだけに着目することで小さいと判断される現象を Editors (\protect\hyperlink{ref-editors2005}{2005}) はアベルソンのパラドックス（Abelson's paradox）と呼んでいる。分野ごとの効果量分布を無視して、Cohenの規準を常に当てはめることは効果量の持つ意味を分かりにくくする。

ところで、Cohenの規準が多くの分野の実際の効果量分布と適合しているのであれば問題はないかもしれないが、実際には適合していないことが多い。例えば、ソフトウェア工学分野の92の実験をレビューした Kampenes et al. (\protect\hyperlink{ref-kampenes2007}{2007}) は、効果量の分布が全体的にCohenの規準よりも大きいことを指摘している。このように分野における効果量分布がCohenの規準と適合していないのであれば、やはりCohenの規準の使用を正当化する理由はないだろう。

研究者は、得られた効果量を現実的な文脈や研究分野ごとの文脈に位置づけることでその実質的な意味を解釈すべきであり、Cohenの規準のようなベンチマークを機械的に当てはめて解釈を放棄することは望ましくない。しかしながら、Cohenの基準は今なお多くの研究で使い続けられている。そして、Cohenの基準を批判する研究者も、その後、Cohenの規準に代わるさらなるベンチマークを開発していくことになる。

\hypertarget{ux5206ux91ceux3054ux3068ux306bux7d30ux5206ux5316ux3055ux308cux305fux898fux6e96}{%
\section{分野ごとに細分化された規準}\label{ux5206ux91ceux3054ux3068ux306bux7d30ux5206ux5316ux3055ux308cux305fux898fux6e96}}

Cohenの規準への批判は、Cohenの規準に代わる新しいベンチマークを生み出すことにつながった。新しいベンチマークの修正の方向性は主に３点にまとめられる。１点目は、Cohenの基準の段階をより細かくすることである。２点目は、分野を限定し、過去の知見から経験的に段階を設定することである。

Sawilowsky (\protect\hyperlink{ref-sawilowsky2009}{2009}) は、近年のメタ分析によって得られた効果量の値が大きくなっていることを根拠に、Cohenの基準を以下のようにプラスの方向に拡張することを提案している。これは、従来のCohenの規準で大きいとみなされていた効果量をさらに細かく段階分けするという修正である。

\begin{longtable}[]{@{}cccc@{}}
\caption{Sawilowsky の基準(\protect\hyperlink{ref-sawilowsky2009}{Sawilowsky, 2009})}\tabularnewline
\toprule
d & 判定 & d & 判定 \\
\midrule
\endfirsthead
\toprule
d & 判定 & d & 判定 \\
\midrule
\endhead
d \textless{} 0.1 & Tiny & 0.8 \textless= d \textless{} 1.2 & Large \\
0.1 \textless= d \textless{} 0.2 & Very small & 1.2 \textless= d \textless{} 2 & Very large \\
0.2 \textless= d \textless{} 0.5 & Small & d \textgreater= 2 & Huge \\
0.5 \textless= d \textless{} 0.8 & Medium & & \\
\bottomrule
\end{longtable}

Gignac \& Szodorai (\protect\hyperlink{ref-gignac2016}{2016}) は、心理的な構成概念や行動の相関に関する708件のメタ分析を収集した結果、この分野の効果量分布はCohenの基準よりもより小さいものであることを明らかにした。そして、相関係数rの判断基準を以下のように修正することを提案した。これは、分野の実態に合わせて効果量分布をマイナス方向へシフトさせるという修正である。

\begin{longtable}[]{@{}lll@{}}
\caption{Gignac \& Szodorai の基準(\protect\hyperlink{ref-gignac2016}{Gignac \& Szodorai, 2016})}\tabularnewline
\toprule
判定 & Cohen (\protect\hyperlink{ref-cohen1988}{1988}) & Gignac \& Szodorai (\protect\hyperlink{ref-gignac2016}{2016}) \\
\midrule
\endfirsthead
\toprule
判定 & Cohen (\protect\hyperlink{ref-cohen1988}{1988}) & Gignac \& Szodorai (\protect\hyperlink{ref-gignac2016}{2016}) \\
\midrule
\endhead
Very small & r \textless{} 0.1 & r \textless{} 0.1 \\
Small & 0.1 \textless= r \textless{} 0.3 & 0.1 \textless= r \textless{} 0.2 \\
Moderate & 0.3 \textless= r \textless{} 0.5 & 0.2 \textless= r \textless{} 0.3 \\
Large & r \textgreater= 0.5 & r \textgreater= 0.3 \\
\bottomrule
\end{longtable}

その他にも、心理学(\protect\hyperlink{ref-funder2019}{Funder \& Ozer, 2019})や社会心理学(\protect\hyperlink{ref-lovakov2021}{Lovakov \& Agadullina, 2021})といった分野特有の規準が提案されてきた。また、老年学(\protect\hyperlink{ref-brydges2019}{Brydges, 2019})や教育介入(\protect\hyperlink{ref-kraft2020}{Kraft, 2020})といったより細かな分野ごとの基準も提案されている。

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.3472}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.3472}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.3056}}@{}}
\caption{各分野ごとの基準}\tabularnewline
\toprule
\begin{minipage}[b]{\linewidth}\raggedright
Funder \& Ozer (\protect\hyperlink{ref-funder2019}{2019})
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Lovakov \& Agadullina (\protect\hyperlink{ref-lovakov2021}{2021})
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Kraft (\protect\hyperlink{ref-kraft2020}{2020})
\end{minipage} \\
\midrule
\endfirsthead
\toprule
\begin{minipage}[b]{\linewidth}\raggedright
Funder \& Ozer (\protect\hyperlink{ref-funder2019}{2019})
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Lovakov \& Agadullina (\protect\hyperlink{ref-lovakov2021}{2021})
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Kraft (\protect\hyperlink{ref-kraft2020}{2020})
\end{minipage} \\
\midrule
\endhead
r \textless{} 0.05 - Tiny & & \\
0.05 \textless= r \textless{} 0.1 - Very small & r \textless{} 0.12 - Very small & \\
0.1 \textless= r \textless{} 0.2 - Small & 0.12 \textless= r \textless{} 0.24 - Small & d \textless{} 0.05 - Small \\
0.2 \textless= r \textless{} 0.3 - Medium & 0.24 \textless= r \textless{} 0.41 - Moderate & 0.05 \textless= d \textless{} 0.2 - Medium \\
0.3 \textless= r \textless{} 0.4 - Large & r \textgreater= 0.41 - Large & 0.2 \textless= d - Large \\
r \textgreater= 0.4 - Very large & & \\
\bottomrule
\end{longtable}

しかし、各分野ごとの経験データから効果量の判断基準が作成されたからといって、それらが適切とは限らない。第一に、各分野の中でも研究テーマごとに効果量分布が大きく異なる可能性がある。第二に、集められた経験データそのものが歪められている可能性がある。例えば、Schäfer \& Schwarz (\protect\hyperlink{ref-schuxe4fer2019}{2019}) は心理学分野の研究からランダムに収集した効果量の分布が事前登録の有無によって異なることを指摘している。このように、判断基準の作成に使用されたデータが真の効果量分布を捉えていなければ、そこから作成された判断基準も誤ったものになる。

Rを使えば、各基準に基づいて効果量の大きさを判断できる。※ここまでの記述内容を踏まえて適切に使用すること。

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 平均値差のデータ}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{55}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{10}\NormalTok{)}

\CommentTok{\# Cohen\textquotesingle{}s d\_s}
\FunctionTok{library}\NormalTok{(effectsize)}
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{cohens\_d}\NormalTok{(A, B)}
\CommentTok{\# Cohen (1988) の基準}
\FunctionTok{interpret\_cohens\_d}\NormalTok{(d, }\AttributeTok{rules =} \StringTok{"cohen1988"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI | Interpretation
## -----------------------------------------
## 0.74      | [0.45, 1.03] |         medium
## 
## - Estimated using pooled SD.
## - Interpretation rule: cohen1988
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Sawilowsky (2009) の基準}
\FunctionTok{interpret\_cohens\_d}\NormalTok{(d, }\AttributeTok{rules =} \StringTok{"sawilowsky2009"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI | Interpretation
## -----------------------------------------
## 0.74      | [0.45, 1.03] |         medium
## 
## - Estimated using pooled SD.
## - Interpretation rule: sawilowsky2009
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Gignac \& Szodorai (2016) の基準}
\FunctionTok{interpret\_cohens\_d}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{Cohens\_d, }\AttributeTok{rules =} \StringTok{"gignac2016"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "large"
## (Rules: gignac2016)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Lovakov \& Agadullina (2021) の基準}
\FunctionTok{interpret\_cohens\_d}\NormalTok{(d, }\AttributeTok{rules =} \StringTok{"lovakov2021"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Cohen's d |       95% CI | Interpretation
## -----------------------------------------
## 0.74      | [0.45, 1.03] |          large
## 
## - Estimated using pooled SD.
## - Interpretation rule: lovakov2021
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 相関のデータ}
\FunctionTok{library}\NormalTok{(mvtnorm)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{sigma }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{100}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{100}\NormalTok{), }\AttributeTok{byrow=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{ncol=}\DecValTok{2}\NormalTok{) }
\NormalTok{mu }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{50}\NormalTok{, }\DecValTok{60}\NormalTok{)}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{100}
\NormalTok{dat }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\FunctionTok{rmvnorm}\NormalTok{(}\AttributeTok{n=}\NormalTok{n, }\AttributeTok{mean=}\NormalTok{mu, }\AttributeTok{sigma=}\NormalTok{sigma)) }

\CommentTok{\# ピアソンの積率相関}
\FunctionTok{library}\NormalTok{(correlation)}
\NormalTok{r }\OtherTok{\textless{}{-}} \FunctionTok{correlation}\NormalTok{(dat)}\SpecialCharTok{$}\NormalTok{r}
\CommentTok{\# Cohen (1988) の基準}
\FunctionTok{interpret\_r}\NormalTok{(r, }\AttributeTok{rules =} \StringTok{"cohen1988"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "moderate"
## (Rules: cohen1988)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Gignac \& Szodorai (2016) の基準}
\FunctionTok{interpret\_r}\NormalTok{(r, }\AttributeTok{rules =} \StringTok{"gignac2016"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "large"
## (Rules: gignac2016)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Funder \& Ozer (2019) の基準}
\FunctionTok{interpret\_r}\NormalTok{(r, }\AttributeTok{rules =} \StringTok{"funder2019"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "large"
## (Rules: funder2019)
\end{verbatim}

\hypertarget{ux30e1ux30bfux5206ux6790}{%
\chapter{メタ分析}\label{ux30e1ux30bfux5206ux6790}}

\begin{itemize}
\item
  理想的には、各研究に関連する先行研究の効果量をメタ分析によって統合し、得られた効果量分布に基づいて効果量の大きさを解釈するべきである。しかしながら、メタ分析においても様々な問題から、真の効果量分布を捉えられないことがある。
\item
  メタ分析は、先行研究から効果量を収集し、それらを評価した上で、特定のモデルによって統合するという手順で実施される。これらの過程において、どのような方法を採用するかに多くの研究者自由度がある。
\item
  効果量の収集段階では、どのような文献を対象にするかを研究者が決定する必要がある。査読付き論文の方が研究の質は高いかもしれないが、出版バイアスの影響で効果量分布を高く見積もる可能性がある。いわゆる灰色文献と呼ばれるような学位論文や紀要論文といった幅広い文献から効果量を収集した方が真の効果量分布に近づくかもしれない。また、英語で書かれた文献のみを収集すれば、効果量分布の一般化可能性を低下させるかもしれない。
\item
  効果量の質の評価の段階では、外れ値を評価して分析から除外する必要があるが、外れ値の検出方法にも様々な方法がある。例えば、外部標準化残差、クック距離、共分散比率、leave-one-out法、Graphic Display of Heterogeneity plotなど、様々な判断基準がある。また、出版バイアスの補正方法も、Egger検定、Petersの回帰検定、Trim \& Fill法、PET-PEESE法、Pカーブ分析、など様々な方法があるが、どの方法を採用するかによって推定される効果量分布は変わってくる。
\item
  効果量を統合する際に使用するモデルにも、固定効果モデル、変量効果モデル、3-levelのマルチレベルモデルなど、様々な方法がある。推定法にも、DerSimonian-Laird、REML、Paule-Mandel、Empirical Bayes、Sidik-Jonkman、など様々な方法があり、効果量推定の不確実性にもどのような分布を適応させるかの選択肢がある（e.g., Knapp-Hartungの調整）。
\item
  このように、メタ分析を行う上では研究者が決定しなければいけない様々な分析の選択肢があり、選択によって推定される効果量の分布が変わってくる。また、そもそも出版バイアスがある場合、効果量の真の分布をとらえることは極めて困難である。
\item
  メタ分析の結果が真の効果量分布を捉えられていないならば、それを効果量の解釈の基準にすることには誤った解釈につながるというリスクが伴う。それでも、ベンチマークを機械的に当てはめることよりはましな推論ができるかもしれないが。
\end{itemize}

\hypertarget{ux691cux5b9aux529bux5206ux6790}{%
\chapter{検定力分析}\label{ux691cux5b9aux529bux5206ux6790}}

後で加筆。最小関心効果量（SESOI）とかにも触れる。

\hypertarget{ux5f15ux7528ux6587ux732eux30eaux30b9ux30c8}{%
\chapter{引用文献リスト}\label{ux5f15ux7528ux6587ux732eux30eaux30b9ux30c8}}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-anvari2021}{}}%
Anvari, F., Kievit, R., Lakens, D., Pennington, C. R., Przybylski, A. K., Tiokhin, L., Wiernik, B. M., \& Orben, A. (2021). \emph{Not all effects are indispensable: Psychological science requires verifiable lines of reasoning for whether an effect matters.} \url{http://dx.doi.org/10.31234/osf.io/g3vtr}

\leavevmode\vadjust pre{\hypertarget{ref-american2019publication}{}}%
APA. (2019). \emph{Publication manual of the american psychological association, seventh edition}. American Psychological Association.

\leavevmode\vadjust pre{\hypertarget{ref-baguley2009}{}}%
Baguley, T. (2009). Standardized or simple effect size: What should be reported? \emph{British Journal of Psychology}, \emph{100}(3), 603--617. \url{https://doi.org/10.1348/000712608x377117}

\leavevmode\vadjust pre{\hypertarget{ref-brydges2019}{}}%
Brydges, C. R. (2019). Effect Size Guidelines, Sample Size Calculations, and Statistical Power in Gerontology. \emph{Innovation in Aging}, \emph{3}(4). \url{https://doi.org/10.1093/geroni/igz036}

\leavevmode\vadjust pre{\hypertarget{ref-cohen1977statistical}{}}%
Cohen, J. (1977). \emph{Statistical power analysis for the behavioral sciences. Revised edition}.

\leavevmode\vadjust pre{\hypertarget{ref-cohen1988}{}}%
Cohen, J. (1988). \emph{Statistical power analysis for the behavioral sciences}. L. Erlbaum Associates.

\leavevmode\vadjust pre{\hypertarget{ref-cumming2012understanding}{}}%
Cumming, G. (2012). \emph{Understanding the new statistics: Effect sizes, confidence intervals, and meta-analysis}. Routledge.

\leavevmode\vadjust pre{\hypertarget{ref-cummings2011}{}}%
Cummings, P. (2011). Arguments for and Against Standardized Mean Differences (Effect Sizes). \emph{Archives of Pediatrics \& Adolescent Medicine}, \emph{165}(7), 592. \url{https://doi.org/10.1001/archpediatrics.2011.97}

\leavevmode\vadjust pre{\hypertarget{ref-delacre2021}{}}%
Delacre, M., Lakens, D., Ley, C., Liu, L., \& Leys, C. (2021). \emph{Why hedges'g* s based on the non-pooled standard deviation should be reported with welch's t-test}. \url{https://doi.org/10.31234/osf.io/tu6mp}

\leavevmode\vadjust pre{\hypertarget{ref-dragicevic2020mean}{}}%
Dragicevic, P. (2020). \emph{A mean difference is an effect size} {[}PhD thesis{]}. Inria Saclay Ile de France.

\leavevmode\vadjust pre{\hypertarget{ref-editors2005}{}}%
Editors, J. (2005). Letter to the Editor: Abelson{'}s Paradox And The Michelson-Morley Experiment. \emph{Journal of Modern Applied Statistical Methods}, \emph{4}(1), 352--352. \url{https://doi.org/10.22237/jmasm/1114907520}

\leavevmode\vadjust pre{\hypertarget{ref-everitt2010cambridge}{}}%
Everitt, B. S., \& Skrondal, A. (2010). \emph{The cambridge dictionary of statistics}.

\leavevmode\vadjust pre{\hypertarget{ref-funder2019}{}}%
Funder, D. C., \& Ozer, D. J. (2019). Evaluating Effect Size in Psychological Research: Sense and Nonsense. \emph{Advances in Methods and Practices in Psychological Science}, \emph{2}(2), 156--168. \url{https://doi.org/10.1177/2515245919847202}

\leavevmode\vadjust pre{\hypertarget{ref-gignac2016}{}}%
Gignac, G. E., \& Szodorai, E. T. (2016). Effect size guidelines for individual differences researchers. \emph{Personality and Individual Differences}, \emph{102}, 74--78. \url{https://doi.org/10.1016/j.paid.2016.06.069}

\leavevmode\vadjust pre{\hypertarget{ref-glass1981}{}}%
Glass, G. V., McGaw, B., \& Smith, M. L. (1981). \emph{Meta-analysis in social research}. SAGE Publications.

\leavevmode\vadjust pre{\hypertarget{ref-grissom2001}{}}%
Grissom, R. J., \& Kim, J. J. (2001). Review of assumptions and problems in the appropriate conceptualization of effect size. \emph{Psychological Methods}, \emph{6}(2), 135--146. \url{https://doi.org/10.1037/1082-989x.6.2.135}

\leavevmode\vadjust pre{\hypertarget{ref-grissom2005}{}}%
Grissom, R. J., \& Kim, J. J. (2005). \emph{Effect sizes for research: A broad practical approach}. Lawrence Erlbaum Associates. \url{https://books.google.co.jp/books?id=4C49CGkNxLAC}

\leavevmode\vadjust pre{\hypertarget{ref-hedges1981}{}}%
Hedges, L. V. (1981). Distribution theory for glass's estimator of effect size and related estimators. \emph{Journal of Educational Statistics}, \emph{6}(2), 107. \url{https://doi.org/10.2307/1164588}

\leavevmode\vadjust pre{\hypertarget{ref-hedges1985}{}}%
Hedges, L. V., \& Olkin, I. (1985). \emph{Statistical methods for meta-analysis}. Academic press.

\leavevmode\vadjust pre{\hypertarget{ref-huberty2002}{}}%
Huberty, C. J. (2002). A History of Effect Size Indices. \emph{Educational and Psychological Measurement}, \emph{62}(2), 227--240. \url{https://doi.org/10.1177/0013164402062002002}

\leavevmode\vadjust pre{\hypertarget{ref-hunter2004}{}}%
Hunter, J. E., Schmidt, F. L., \& Sage Publications, inc. (2004). \emph{Methods of meta-analysis: Correcting error and bias in research findings}. SAGE Publications. \url{https://books.google.co.jp/books?id=kImkui18i94C}

\leavevmode\vadjust pre{\hypertarget{ref-ialongo2016}{}}%
Ialongo, C. (2016). Understanding the effect size and its measures. \emph{Biochemia Medica}, 150--163. \url{https://doi.org/10.11613/bm.2016.015}

\leavevmode\vadjust pre{\hypertarget{ref-ives2003}{}}%
Ives, B. (2003). Effect Size Use in Studies of Learning Disabilities. \emph{Journal of Learning Disabilities}, \emph{36}(6), 490--504. \url{https://doi.org/10.1177/00222194030360060101}

\leavevmode\vadjust pre{\hypertarget{ref-kampenes2007}{}}%
Kampenes, V. B., Dybå, T., Hannay, J. E., \& Sjøberg, D. I. K. (2007). A systematic review of effect size in software engineering experiments. \emph{Information and Software Technology}, \emph{49}(11-12), 1073--1086. \url{https://doi.org/10.1016/j.infsof.2007.02.015}

\leavevmode\vadjust pre{\hypertarget{ref-kelley2012}{}}%
Kelley, K., \& Preacher, K. J. (2012). On effect size. \emph{Psychological Methods}, \emph{17}(2), 137--152. \url{https://doi.org/10.1037/a0028086}

\leavevmode\vadjust pre{\hypertarget{ref-kirk1996}{}}%
Kirk, R. E. (1996). Practical Significance: A Concept Whose Time Has Come. \emph{Educational and Psychological Measurement}, \emph{56}(5), 746--759. \url{https://doi.org/10.1177/0013164496056005002}

\leavevmode\vadjust pre{\hypertarget{ref-kline2004}{}}%
Kline, R. B. (2004). \emph{Beyond significance testing: Reforming data analysis methods in behavioral research.} American Psychological Association. \url{https://doi.org/10.1037/10693-000}

\leavevmode\vadjust pre{\hypertarget{ref-kraft2020}{}}%
Kraft, M. A. (2020). Interpreting Effect Sizes of Education Interventions. \emph{Educational Researcher}, \emph{49}(4), 241--253. \url{https://doi.org/10.3102/0013189x20912798}

\leavevmode\vadjust pre{\hypertarget{ref-lakens2013}{}}%
Lakens, D. (2013). Calculating and reporting effect sizes to facilitate cumulative science: A practical primer for t-tests and ANOVAs. \emph{Frontiers in Psychology}, \emph{4}. \url{https://doi.org/10.3389/fpsyg.2013.00863}

\leavevmode\vadjust pre{\hypertarget{ref-lenth2001}{}}%
Lenth, R. V. (2001). Some Practical Guidelines for Effective Sample Size Determination. \emph{The American Statistician}, \emph{55}(3), 187--193. \url{https://doi.org/10.1198/000313001317098149}

\leavevmode\vadjust pre{\hypertarget{ref-lovakov2021}{}}%
Lovakov, A., \& Agadullina, E. R. (2021). Empirically derived guidelines for effect size interpretation in social psychology. \emph{European Journal of Social Psychology}, \emph{51}(3), 485--504. \url{https://doi.org/10.1002/ejsp.2752}

\leavevmode\vadjust pre{\hypertarget{ref-mcgrath2006}{}}%
McGrath, R. E., \& Meyer, G. J. (2006). When effect sizes disagree: The case of r and d. \emph{Psychological Methods}, \emph{11}(4), 386--401. \url{https://doi.org/10.1037/1082-989x.11.4.386}

\leavevmode\vadjust pre{\hypertarget{ref-mcgraw1992}{}}%
McGraw, K. O., \& Wong, S. P. (1992). A common language effect size statistic. \emph{Psychological Bulletin}, \emph{111}(2), 361--365. \url{https://doi.org/10.1037/0033-2909.111.2.361}

\leavevmode\vadjust pre{\hypertarget{ref-nakagawa2007}{}}%
Nakagawa, S., \& Cuthill, I. C. (2007). Effect size, confidence interval and statistical significance: a practical guide for biologists. \emph{Biological Reviews}, \emph{82}(4), 591--605. \url{https://doi.org/10.1111/j.1469-185x.2007.00027.x}

\leavevmode\vadjust pre{\hypertarget{ref-preacher2011}{}}%
Preacher, K. J., \& Kelley, K. (2011). Effect size measures for mediation models: Quantitative strategies for communicating indirect effects. \emph{Psychological Methods}, \emph{16}(2), 93--115. \url{https://doi.org/10.1037/a0022658}

\leavevmode\vadjust pre{\hypertarget{ref-rosenthal1994}{}}%
Rosenthal, R. (1994). PARAMETRIC MEASURES OF EFFECT SIZE. In \emph{The handbook of research synthesis} (pp. 231--244). Russell Sage Foundation. \url{http://www.jstor.org/stable/10.7758/9781610441377.20}

\leavevmode\vadjust pre{\hypertarget{ref-sawilowsky2009}{}}%
Sawilowsky, S. S. (2009). New Effect Size Rules of Thumb. \emph{Journal of Modern Applied Statistical Methods}, \emph{8}(2), 597--599. \url{https://doi.org/10.22237/jmasm/1257035100}

\leavevmode\vadjust pre{\hypertarget{ref-schuxe4fer2019}{}}%
Schäfer, T., \& Schwarz, M. A. (2019). The meaningfulness of effect sizes in psychological research: Differences between sub-disciplines and the impact of potential biases. \emph{Frontiers in Psychology}, \emph{10}. \url{https://doi.org/10.3389/fpsyg.2019.00813}

\leavevmode\vadjust pre{\hypertarget{ref-vandekar2020}{}}%
Vandekar, S., Tao, R., \& Blume, J. (2020). A Robust Effect Size Index. \emph{Psychometrika}, \emph{85}(1), 232--246. \url{https://doi.org/10.1007/s11336-020-09698-2}

\leavevmode\vadjust pre{\hypertarget{ref-wilkinson1999}{}}%
Wilkinson, L. (1999). Statistical methods in psychology journals: Guidelines and explanations. \emph{American Psychologist}, \emph{54}(8), 594--604. \url{https://doi.org/10.1037/0003-066x.54.8.594}

\leavevmode\vadjust pre{\hypertarget{ref-inoue2008}{}}%
井上俊哉. (2008). ブートストラップ BCa 法による効果量 \(\delta\) の信頼区間. \emph{東京家政大学研究紀要 1 人文社会科学}, \emph{48}, 1--7. \url{http://id.nii.ac.jp/1653/00009232/}

\leavevmode\vadjust pre{\hypertarget{ref-haebara2014}{}}%
南風原朝和. (2014). \emph{続・心理統計学の基礎: 統合的理解を広げ深める}. 有斐閣. \url{https://books.google.co.jp/books?id=h-vFrQEACAAJ}

\leavevmode\vadjust pre{\hypertarget{ref-haebara1987}{}}%
南風原朝和, \& 芝祐順. (1987). 相関係数および平均値差の解釈のための確率的な指標. \emph{教育心理学研究}, \emph{35}(3), 259--265.

\leavevmode\vadjust pre{\hypertarget{ref-ux5c71ux75302020}{}}%
山田剛史. (2020). 単一事例データのための統計的方法について─ 効果量を中心に─. \emph{高齢者のケアと行動科学}, \emph{25}, 35--55. \url{https://doi.org/10.24777/jsbse.25.0_35}

\end{CSLReferences}

\end{document}
